### ISSUE TITLE
Gatsby build fails with cannot read property 'finalForm' of null

### ISSUE THREAD

**Issue by spbyrne** [tinacms/tinacms#1054]
## Description

When using InlineForm with Gatsby, the build process fails. @kendallstrautman explained it's likely because [useRemarkForm returns [markdown,null] in production](https://github.com/tinacms/tinacms/blob/5e11cb97730d84b1507ec8758b45fe2a9a4bf6e8/packages/gatsby-tinacms-remark/src/useRemarkForm.tsx#L52-L54) and the inline form doesn't expect the null value.

The problem occurs only once `InlineForm` is added to the page.

### Steps to reproduce

Here's a test case: https://github.com/spbyrne/final-form-null

### Expected result

When you run `gatsby build`, it should build successfully. 

### Actual result

```
WebpackError: TypeError: Cannot read property 'finalForm' of null
  
  - index.js:1 a
    node_modules/@tinacms/form-builder/build/index.js:1:733
```

**Comment by kendallstrautman** [comment]
This early return was implemented as a [perf improvement](https://github.com/tinacms/tinacms/issues/269). It was not anticipating `InlineForm` needing access to the form object even in production.

The possible fixes for this are tricky because they inherently come with a bigger conversation around how we provide the option to `disable` Tina and minimize overhead.

The easiest way I see to fix this is to have `useRemarkForm` and `useJsonForm` return forms in production — as was done with `useForm`, see #520. We could then try to find higher-level ways for the dev to minimize Tina code depending on their particular environment.

**Comment by ncphillips** [comment]
I'd be up for creating the form in production, but there's some complications. Namely, `useRemarkForm` tries to make requests to `@tinacms/api-git` and that won't fly in production. So I guess it might be a matter of creating the form but disabling those behaviours instead.
