### ISSUE TITLE
Focus ring for inline wysiwyg field

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#1347]
**Issue**
Help editors understand when they can start typing in the editor, this issue was spotted during user testing session, it's easy to think you type in the editor, when you haven't, because it's hard to tell.

**Demo**
https://www.loom.com/share/349ca847002843dba5bafdaa7127cc0a

**Expected**

> It would probably make sense to at least have the same focus ring API on the wysiwyg inline field, even if we decide to default it to 'false'. The current inline field focus ring is out of date and it needs to be updated to match the 'new' focus ring used on inline blocks. — @spbyrne

**Comment by jpuri** [comment]
Adding a focus style around editor while user is editing is feasible and quick thing.

Another nice improvement could be showing some placeholder text like `Start typing here...` but that is bit more detailed implementation for wysiwyg.

**Comment by DirtyF** [comment]
@jpuri Let's focus on the ring on this PR.

Inline blocks have a `defaultItem` props, this could be something developers could opt-in if they want to provde a default content. 

@kendallstrautman would that make sense tto provide similar props to the inline wysiwyg field?

**Comment by kendallstrautman** [comment]
@jpuri here is the focus ring we use for the [inline blocks](https://github.com/tinacms/tinacms/blob/master/packages/react-tinacms-inline/src/styles/focus-ring.tsx) as an API reference.

I think providing a default text callback could be cool and useful. It's necessary for blocks since users can add new ones that may need placeholder data so the components don't break, but I'm wondering if that will be a usecase for this field? If anything we could just hard-code some default text to start and then see if it's something people are wanting later on.
