### ISSUE TITLE
Ensure dependencies are correct

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#1360]
## Description

While working with yarn v2 (with Plug-n-Play) it becomes immediately obvious that there are a lot of missing dependency declarations in Tina. Yarn with plug-n-play (and others like pnpm) won't load undeclared transitive dependencies, and it gives a pretty decent error report. Through that I've managed to get Tina working but most of these fixes should be handled in the packages themselves. What I've seen for the most part is we have lots of packages which import a module and don't list it as a peer dependency or a dependency - I think these should be treated as bugs.

### Example

An example is `@tinacms/fields` not declaring `@tinacms/form-builder` as a dependency.

It's declared as a devDependency [here](https://github.com/tinacms/tinacms/blob/859b8db0eb7cc63825e51bff0a1d024e5398135c/packages/@tinacms/fields/package.json#L35) but that doesn't help. [Here](https://github.com/tinacms/tinacms/blob/9f33387edea51e01b145f7b8d7e474717664c827/packages/@tinacms/fields/src/plugins/GroupListFieldPlugin.tsx#L22)'s where it's being used.

### Steps to reproduce

I've created a repo [here](https://github.com/jeffsee55/tina-dependency-reproduction). In one folder is a next.js app with Tina, and in the other is the identical app with yarn v2. If you have any issues running yarn let me know.

### Expected result

The app should boot up, but it throws dependency errors and won't resolve them. I've fixed these in the `.yarnrc.yml` file but I have them commented out for demonstration purposes. Uncommenting the `packageExtensions` should result in a successful build.

**Comment by ncphillips** [comment]
The issue I have is figuring out what the "correct dependencies" even means.

Let's say  `react-tinacms-editor` has `@tinacms/react-core` as a `peerDependency`. 

If I install `tinacms` then `@tinacms/react-core` _is_ installed, but `npm install` will still throw a warning that `react-tinacms-editor` is missing `@tinacms/react-core` as a `peerDependency` even though there will be no problem when running the code.

Well what if I just make `@tinacms/react-core` a `dependency` of `react-tinacms-editor`? That can work sometimes, but because `@tinacms/react-core` declares a `React.createContext` I can run into big trouble. If by change that package gets installed in the `node_modules` in two instances then you'll start seeing really funky bugs because React's Context objects are singletons per installed package. 

Since we just switched to fixed versioning, making everything a `dependency` rather then a `peerDependency` could be viable now.

**Comment by jeffsee55** [comment]
> Let's say `react-tinacms-editor` has `@tinacms/react-core` as a `peerDependency`.
If I install `tinacms` then `@tinacms/react-core` is installed, but `npm install` will still throw a warning that `react-tinacms-editor` is missing `@tinacms/react-core` as a `peerDependency` even though there will be no problem when running the code.

I'm not sure that's the best example because from what I can see `react-tinacms-editor` doesn't import anything from `@tinacms/react-core`. Also - are you saying it would still throw that warning if you **did** list it in your peer dependencies? I'm saying I don't think that would be the case.

But in theory if `react-tinacms-editor` did import something from `@tinacms/react-core` what I'm saying is that it **should** be listed as a `peerDependency`. The problem here is that the peer dependency is implicit. By declaring it as a `peerDependency` we're telling the package manager that we acknowledge we are using this module in our runtime code so make sure you get it from one of our parents. I get it that it's a pain but that's the downside of having a lot of different packages. 

> even though there will be no problem when running the code.

For some package managers there will be a problem running the code. Since node has no concept of “package”, it doesn’t know whether a file is meant to be accessed, the example you provided wont work on pnpm or yarn pnp. I think it's ok to be loose the peer dependencies if you're the end user but as a package we don't have that luxury.

And yes I agree that you shouldn't make `@tinacms/react-core` a **dependency** of `react-tinacms-editor` because it's also a dependency of `tinacms`. I understand your point about duplicate singleton issues - I think in general most **dependencies** should be declared in the `tinacms` package, while the others should mostly have `peerDependencies`.  And then of course above `tinacms` it makes sense that you need to declare the big dogs on your own (`react`, `react-dom`, and I guess `styled-components`)

**Comment by estrogently** [comment]
> 
> The issue I have is figuring out what the "correct dependencies" even means.
> 

At least in the context of Yarn PnP (which as of today Tina still does not seem compatible with), it means

1. Every package you use must be declared explicitly as either a dependency or a peer dependency.
2. If you depend on a package with peer dependencies, you must explicitly declare its peer dependencies as either dependencies or peer dependencies of your own.

Two examples of an incorrect setup:
- Package A uses React and package B, and lists both as dependencies.
- Package B uses React, and does not list it as a dependency or peer dependency.

This won't work, because package B needs to explicitly declare React a (peer) dependency.

- Package A uses React and package B, and lists both as dependencies.
- Package B uses package C, and lists it as a dependency.
- Package C uses React, and lists it as a peer dependency.

This won't work, because C's lookup for React stops at B. For it to use A's version of React, B needs to declare React a peer dependency.
