### ISSUE TITLE
`TinaProvider` remounts children on enabled / disabled

### ISSUE THREAD

**Issue by kendallstrautman** [tinacms/tinacms#1366]
## Description

Noticed this during the getting started tutorial set up and wanted to make an issue so we don't forget. When toggling enabled states, the entire app will be remounted since the `TinaProvider` is rendering it without the UI and theme etc.

This may not necessarily be a bug, but it's not ideal. Not sure how we'd get around this — something to think about.

### Steps to reproduce

Add a console.log on a page component on initial mount. Toggle edit mode and you'll see it remounts.

**Comment by ncphillips** [comment]
I believe this bug only really happens if you're using the `Sidebar` component. 

Lauren started [a topic in the forum](https://community.tinacms.org/t/tina-sidebar-is-there-any-way-to-have-the-boolean-inside-the-config/302) describing a similar thing. In her case the remounting was preventing the Strapi authentication modal from being rendered. 

The issue is coming from the [TinaProvider](https://github.com/tinacms/tinacms/blob/master/packages/tinacms/src/components/TinaProvider.tsx#L63-L69) where we selectively render the children either inside of the Sidebar or not. A similar issue may arise because of the site-wrapping logic [here](https://github.com/tinacms/tinacms/blob/master/packages/@tinacms/react-sidebar/src/components/Sidebar.tsx#L50-L54)
