### ISSUE TITLE
Prevent cms from fully enabling before auth is complete

### ISSUE THREAD

**Issue by chrisdmacrae** [tinacms/tinacms#1636]
## Summary

Have auth workflows run prior to the cms enabling. 

### Basic example

Right now auth modals are bound to the enable event. This means they open up and the cms chrome and enabled logic runs behind the modal. 

This feels clunky in workflows that lead to a window refresh. 

It also means that the in between state can break if anything in the enabled editing mode is expecting the oauth token. 

### Motivation

Better developer and editor experience through defensive design.

**Comment by dwalkr** [comment]
The way auth works now is, I presume, based largely around arbitrary conventions established by `react-tinacms-github`. There's a lot of room for improvement here. I agree that it being coupled to `cms.enabled` isn't ideal.

It's worth noting that it is entirely up to the package developer to decide how auth should work; we just don't have many useful events to attach to besides `cms:enable`.

This suggestion feels a bit premature - we need better scaffolding for setting up auth inside of TinaCMS before we can talk productively about this, otherwise things will continue to be poorly defined and ad-hoc.

Definitely RFC territory IMO!

**Comment by chrisdmacrae** [comment]
@dwalkr good suggestion. We should probably consider #1445 at the same time in an RFC.
