### ISSUE TITLE
Allow multiple media stores to be registered, but maintain a single active store

### ISSUE THREAD

**Issue by chrisdmacrae** [tinacms/tinacms#1637]
## Summary

Based on the limitations of a media provider or media stored in multiple places, a single TinaCMS instance may need to talk to multiple media stores. 

### Basic example

Leave behaviour as-is if there is only one media manager. 

To add multiple, you assign “stores” instead of “store” as an object with keys or call cms.media.add(id, store)

If there is multiple, treat each as a “directory” and scope into a given store when selecting it. 

Also allow any first party fields to specify which store they open in some way if you want to restrict it. 

### Motivation

Implementing multiple stores on your own is a rats nest. A very basic implementation would be ideal. 

The above implementation still allows someone to create a “media store manager” media store instead of using the default multi-store behaviour, but makes media stores 1:1 with the API functionality.

**Comment by dwalkr** [comment]
When designing the media api we made a deliberate decision that, unlike the `cms.api` namespace, only one media store would be registered at a time.

I suspect adding support for multiple stores would create a lot of problems since it violates a fundamental assumption we made when adding media management.

I'm not saying we can't do it, but can you describe a real-world use case for this?

**Comment by chrisdmacrae** [comment]
@dwalkr 100%. 

- Migrating from some headless CMS to Git incrementally. 
- Storing some media (think, PDFs, etc) in one store while storing images in imgix

I view this as NOT supporting multiple stores at the same time, but having functionality to have multiple registered stores and a single active store at a given time.

**Comment by dwalkr** [comment]
One of the biggest challenges would be with media referenced in markdown content. Since we don't really have anywhere to stash metadata in that format, grabbing a URL and correlating it tonan object in a media store is already a bit tricky - the potential presence of multiple media stores makes this untenable IMO.

In cases where media is stored with different services, I think a custom media store should be created that encapsulates that business logic. i.e. if it's a pdf, load/store it with service X, if it's a jpg, use service Y. In a migration scenario: store all uploads in service Y; if an image is not found in service Y, check service X. These are heuristics that need to exist if multiple media storage services are going to be  used in a single project, and Tina should not try to account for those scenarios.

There's no rule that a single MediaStore needs to map 1:1 to a service or API client!

**Comment by chrisdmacrae** [comment]
@dwalkr that's a fair point -- this may be better off as a reference implementation versus a core feature.
