### ISSUE TITLE
Add an `onChange` hook to field-level configs

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#1669]
## Description

I want an `onChange` event at the field-level - however this isn't supported so I'm instead using `parse` - but running into an issue when trying to do something on list-type fields like `blocks`, `list`, and `group-list`, digging into the code I can see there's no `parse` supplied at this level. 

I understand that `parse` doesn't make any sense for my needs here, I'm proposing that we add an `onChange`, which is a "fire-and-forget" side effect whenever the field's value changes, whether that be a text input or a list.

### Steps to reproduce

Build any form and supply a `parse` prop to an iteratable field type:

```jsx
const formOptions = {
  fields: [
    {
      label: 'Authors List',
      name: 'rawJson.authors',
      component: 'group-list',
      description: 'Authors List',
      parse: () => {console.log("I will never be called")}
      fields: [
        {
          label: 'Name',
          name: 'name',
          component: 'text',
          parse: () => {console.log("I will be called when the text value changes")}
        },
      ],
    },
    //...
  ],
}
```

### Expected result

`parse` runs for iterable fields when the order is changed or when an item is added/removed. I consider this a bug since the Typescript types indicate this is supported.

### Actual result

`parse` never runs, `format` runs too often for my needs.

**Comment by chrisdmacrae** [comment]
@jeffsee55 in my experience, `parse` runs when the data is _being sent to the field component_. `format` runs when the data is being serialized back into the form.

**Comment by jeffsee55** [comment]
@chrisdmacrae Yeah that's my experience too, so parse should be the solution here.. but the issue is that it doesn't trigger for any of our list fields.

**Comment by jeffsee55** [comment]
Dug into this with @chrisdmacrae on Friday, we'd expect an event from final form's `mutator` functions:

For example the block insert doesn't send an event when this happpens:

https://github.com/tinacms/tinacms/blob/master/packages/@tinacms/fields/src/plugins/BlocksFieldPlugin.tsx#L95

And it seems like it might be an issue with final form, not sure if it's __suppposed__ to send an event here

https://github.com/final-form/final-form-arrays/issues/53

**Comment by jeffsee55** [comment]
I've got a workaround for now, but it's pretty messy

**Comment by zenflow** [comment]
@jeffsee55 https://github.com/tinacms/tina-graphql-gateway seems to be a private repository :( Any chance of making it public?

**Comment by jeffsee55** [comment]
Sorry @zenflow but I'm not able to make that one public, it basically pulls the final-form array mutators apart and puts them back together with the addition of a callback that I need. Like I said, very messy - we'll work on getting something like this back into core with less junk

Here's one of the mutators we use as an example https://github.com/final-form/final-form-arrays/blob/master/src/move.js.

the gist is here:

```ts
import finalFormArrays from "final-form-arrays";
import { getIn, setIn } from "final-form";
import type { Form } from "tinacms";

export const fixMutators = (args: {
  callback: () => void;
  form: Form // Tina form instance
}) => {
  const { form, callback } = args;

  const changeValue = (state, name, mutate) => {
    const before = getIn(state.formState.values, name);
    const after = mutate(before);
    state.formState.values = setIn(state.formState.values, name, after) || {};
  };

 export const fixMutators = (args: {
  callback: () => void;
  form: Form // Tina form instance
}) => {
  const { form, callback } = args;

  const changeValue = (state, name, mutate) => {
    const before = getIn(state.formState.values, name);
    const after = mutate(before);
    state.formState.values = setIn(state.formState.values, name, after) || {};
  };

  const { move: moveCopy, remove: removeCopy, insert: insertCopy } = {
    ...form.finalForm.mutators,
  };
  form.finalForm.mutators.move = (name, from, to) => {
    // Grab the value that's being moved 
    const dataValue = getIn(form.values[name], name);
    let state = {
      formState: { values: { fakeValue: dataValue } },
    };
    try {
      // @ts-ignore state is expecting the full final-form state, but we don't need it so we fake it for simplicity
      finalFormArrays.move(["fakeValue", from, to], state, { changeValue });
      // FIXME: this throws an error, probably because of "state" being faked but the mutation works :shrug:
    } catch (e) {
      // This is what you need
      callback(dataValue);
    }

    // Return the copy like nothing ever happened
    return moveCopy(name, from, to);
  };


```

**Comment by Enigmatical** [comment]
### Premise
I stumbled upon this issue and, in the interest of learning more about TinaCMS and Final-Form, decided to take a stab at introducing an `onChange()` hook at the `form` and `field` config levels.  

### Implementation
* `react-final-form` has an optional package: [React-Final-Form-Listeners](https://www.npmjs.com/package/react-final-form-listeners) that provides additional components for things like: `OnFocus`, `OnBlur`, and `OnChange`
* I decided to embed the `<OnChange />` component [here (@tinacms/form-builder/fields-builder.js)](https://github.com/tinacms/tinacms/blob/5df1b54b68e7383ca84f4757ab52b7b181597415/packages/%40tinacms/form-builder/src/fields-builder.tsx#L63), just above the `<FinalField />` component as that seemed the ideal spot to catch every `field` that the `form` would be responsible for.

### Pros
* Initial results were _very_ promising: Most TinaCMS fields (`text`, `number`, `image`, `color`, `toggle`, `markdown`, `tags`, etc) triggered `OnChange` events as expected and provided `field` details, the current `value`, and the `previous` value.

#### Examples

* Modifying a `text` field
```
[OnChange] Emitted by frontmatter.name (text): {"value":"Author","previous":""}
```
* Changing an `image` field via `MediaStore`
```
[OnChange] Emitted by frontmatter.image (image): {"value":"/public/images/iceland-thumb.jpg","previous":"/images/davisco-5E5N49RWtbA-unsplash.jpg"}
```
* Adding a tag to a `tags` field
```
[OnChange] Emitted by tags (tags): {"value":["blocks","123","i-am-pretty-long-tag"],"previous":["123","i-am-pretty-long-tag"]}
```
* Changing a `color` field
```
[OnChange] Emitted by frontmatter.color (color): {"value":"#4A90E2","previous":"#A23232"}
```


### Cons
* Unfortunately, more complex TinaCMS fields (`list`, `group`, `group-list`, `blocks`, etc) resulted in an unusual and (at times) unexpected behavior.

#### List Examples

* Inserting an item to an empty `list`
```
[OnChange] Emitted by frontmatter.lunch (list): {"value":["turkey"],"previous":[]}
```
* Modifying an item in a `list`
```
[OnChange] Emitted by frontmatter.lunch (list): {"value":["hotdogs","turkey"],"previous":["","turkey"]}
[OnChange] Emitted by frontmatter.lunch.0 (text): {"value":"hotdogs","previous":""}
```
* Inserting an item into an existing `list`
```
[OnChange] Emitted by frontmatter.lunch (list): {"value":["pizza","hotdogs","turkey"],"previous":["hotdogs","turkey"]}
[OnChange] Emitted by frontmatter.lunch.0 (text): {"value":"pizza","previous":"hotdogs"}
[OnChange] Emitted by frontmatter.lunch.1 (text): {"value":"hotdogs","previous":"turkey"}
```
* Reordering items in a `list`
```
[OnChange] Emitted by frontmatter.lunch (list): {"value":["hotdogs","turkey","pizza"],"previous":["pizza","hotdogs","turkey"]}
[OnChange] Emitted by frontmatter.lunch.0 (text): {"value":"hotdogs","previous":"pizza"}
[OnChange] Emitted by frontmatter.lunch.1 (text): {"value":"turkey","previous":"hotdogs"}
[OnChange] Emitted by frontmatter.lunch.2 (text): {"value":"pizza","previous":"turkey"}
```

#### Group and Group-List Examples

* Modifying a `text` field on a `group`
```
[OnChange] Emitted by photographer (group): {"value":{"name":"Author"},"previous":""}
[OnChange] Emitted by photographer.name (text): {"value":"Author","previous":""}
```
* Inserting an item into an empty `group-list`
```
[OnChange] Emitted by photographer (group): {"value":{"name":"Author","social":[{}]},"previous":{"name":"Author"}}
[OnChange] Emitted by photographer.social (group-list): {"value":[{}],"previous":""}
```
* Modifying a `text` field on an item in a `group-list` within a `group`
```
[OnChange] Emitted by photographer (group): {"value":{"name":"Author","social":[{"platformName":"LinkedIn"}]},"previous":{"name":"Author","social":[{"platformName":""}]}}
[OnChange] Emitted by photographer.social (group-list): {"value":[{"platformName":"LinkedIn"}],"previous":[{"platformName":""}]}
[OnChange] Emitted by photographer.social.0.platformName (text): {"value":"LinkedIn","previous":""}
```
* Inserting an item into an existing `group-list`
```
[OnChange] Emitted by photographer (group): {"value":{"name":"Author","social":[{},{"platformName":"LinkedIn","account":"Author"}]},"previous":{"name":"Author","social":[{"platformName":"LinkedIn","account":"Author"}]}}
[OnChange] Emitted by photographer.social (group-list): {"value":[{},{"platformName":"LinkedIn","account":"Author"}],"previous":[{"platformName":"LinkedIn","account":"Author"}]}
```
* Reordering items in a `group-list`
```
[OnChange] Emitted by photographer (group): {"value":{"name":"Author","social":[{"platformName":"LinkedIn","account":"Author"},{}]},"previous":{"name":"Author","social":[{},{"platformName":"LinkedIn","account":"Author"}]}}
[OnChange] Emitted by photographer.social (group-list): {"value":[{"platformName":"LinkedIn","account":"Author"},{}],"previous":[{},{"platformName":"LinkedIn","account":"Author"}]}
```

### Outcome

After a handful of team-wide discussions, we've decided to stop _this_ approach to `OnChange` due to two reasons:

* Inconsistent behavior with `list`s and `group-list`s that might actually need to be addressed first

* A general lack of clarity on what exactly is expected, especially when dealing with `list`s and `group`s.

For the second bullet, we bounced back and forth between wanting the entire, updated `Array[]` or `Object{}` and ignoring the individual item events and wanting to ignoring `Array[]` or `Object{}` and only emitting for `string` and `number` values.

In the ideal scenario, we would want better insight to how the `onChange` was triggered:

* An item in a `list` was moved: Only emit the updated `Array[]`, suppress any indivdual item events.
* An item's value was modified: Only emit the individual item event, suppress the updated `Array[]`.

At this point, `react-final-form-listeners` does not provide enough granularity to prevent propogation.

Additionally, when discussing `group` and `group-list`s, there is performance concerns when dealing with a `group` within a `group` within a `group` which Tina allows.  Such situations could result in a massive number of events triggering that might just become noise (and grind Tina to a halt).

**Comment by jeffsee55** [comment]
I've been thinking about this a bit, and while I'm not sure what the easiest solution is - I think the "correct" one is to behave like React does with state - when you change state at the top of the tree, everything below is wiped out and recalculated. In this analogy, our the item in an group or block array triggering `onChange` is invalid because it didn't _change_, it was remounted. 

So while I know that this isn't how it's working right now, I kind of think if we could unmount the subtree and remount it (in a way that does _not_ trigger every item to fire their `onChange` callback) that would be the least bug-prone approach.

**Comment by jeffsee55** [comment]
This will be resolved with the useGraphQLForms refactor https://github.com/tinacms/tinacms/issues/2417
