### ISSUE TITLE
Feat: Github JSON/Markdown content creators for Next and Gatsby

### ISSUE THREAD

**Issue by austincondiff** [tinacms/tinacms#1683]
## Summary

Content creators in these respective packages seems to be currently missing. Making the creation of new content as simple to create a form that syncs up to Github would fill in that missing piece in the API.

**Comment by Chizzah** [comment]
Is this possible yet?

I implemented the nextjs github setup but then wanted to add a blog powered by tinacms afterwards and couldn't get it to work.

**Comment by DirtyF** [comment]
Here's one [example to create Blog Posts on Tina's website](https://github.com/tinacms/tinacms.org/blob/master/tinacms/BlogPostCreator.ts)

**Comment by davidpfahler** [comment]
@DirtyF Thank for the example. I am looking for a way to have editors work on a branch and see the newly created posts while editing on that branch. It seems this is not possible with the solution in tinacms.org's repo, as [`getStaticPaths` only looks into the local file system](https://github.com/tinacms/tinacms.org/blob/3289ab7735ed95fed035fd1d68f4a488df0f97ae/pages/blog/%5Bslug%5D.tsx#L142). Is there a way to serve content from a branch on GitHub, so that editors can work on this content in preview mode, create new content and later merge this content into master/main, which then triggers the actual deployment?
