### ISSUE TITLE
TinaCMS initializer types don't match return types

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#1689]
## Description

The initializer accepts `apis` as an object, but returns `api.[my-api]`. 

### Expected result

I expect it to match the same shape:
```ts
  const cms = new TinaCMS({
    api: {
      myAPI: client,
    },
    sidebar: true,
    enabled: false,
  });

  // grab the api with this:
  cms.api.myAPI
```

### Actual result

```ts
  const cms = new TinaCMS({
    apis: {
      myAPI: client,
    },
    sidebar: true,
    enabled: false,
  });

  // this isn't intuitive
  cms.api.myAPI
```

**Comment by jeffsee55** [comment]
@dwalkr I can tackle this, but which API do want to preserve? Possibly we should keep the functionality entact but throw a console warning against the deprecated one?

**Comment by notjosh** [comment]
My 2c is to use `apis` - we have `plugins`, `events` as plural, so that would seem most consistent.

fwiw, I did find [a reference to `cms.apis`](https://github.com/tinacms/tinacms.org/blob/837cd42566ba70583e4abb4b37e96106a511b300/content/docs/plugins/content-creators.md) in the docs already, so that's one less thing to update later!
