### ISSUE TITLE
Uncaught TypeError: Cannot read property 'contains' of null

### ISSUE THREAD

**Issue by Fi1osof** [tinacms/tinacms#1764]
## Description

With param toolbar: true, i got error on click "Exit Tina". On https://tina-demo-two.vercel.app/ this error exists too.

```js
return d.useEffect(function() {
      function t(e) {
        a || f.current.contains(e.target) || (l || function(e) {
          e.stopPropagation(),
          e.stopImmediatePropagation(),
          e.preventDefault()
        }(e),
        o(e))
      }
```

https://tina-demo-two.vercel.app/static/node_modules/react-dismissible/build/index.js:formatted

### Steps to reproduce

1. Go to https://tina-demo-two.vercel.app/
2. Open browser's console
3. Click "Exit Tina"

Also got it on own project.

### Expected result
No errors

### Actual result
Exception

#### Tinacms Package Versions
tinacms@0.38.0

**Comment by DirtyF** [comment]
This is the console error I get when I exit Tina on demo:

```js
Uncaught TypeError: f.current is null
    e index.js:1
    r index.js:1
    r index.js:1
    Ls React
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    R scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
index.js:1:681
```

**Comment by davidpfahler** [comment]
I am desperately trying to debug this, but to no avail. Can someone please explain to me what the deal is with react-dismissible? I cannot find it anywhere in the current master branch but it seems to this be used within other packages.

**Comment by lautapercuspain** [comment]
Hey Tina team, any solutions for the above issue. I'm getting the same issue. 👀

**Comment by DirtyF** [comment]
> 1.  Go to https://tina-demo-two.vercel.app/
> 2.  Open browser's console
> 3.  Click "Exit Tina"

I can't reproduce the error there.

@lautapercuspain Can you share a reproducible example here?

**Comment by lautapercuspain** [comment]
> > 1. Go to https://tina-demo-two.vercel.app/
> > 2. Open browser's console
> > 3. Click "Exit Tina"
> 
> I can't reproduce the error there.
> 
> @lautapercuspain Can you share a reproducible example here?

@DirtyF If you open the Chrome developer console, after hitting the "Exit Tina" button in the Toolbar, at the right upper corner of the page, you will see the error. It's the same error that happens in development. Something that has to do with **react-dismissable** package. Please address ASAP. This bug is impacting every new Tina installation, and that is a shame because we all know that Tina is AWESOME, right? So, let me know if that is something that you guys would like to address sooner than later. Thank you!


![Uploading Screen Shot 2021-06-04 at 12.09.30.png…]()

**Comment by DirtyF** [comment]
How is it impacting Tina installation? I can't reproduce it on https://tina.io/, I was wondering If this was just something specific to the demo that isn't open to public changes.

**Comment by edridiger** [comment]
I get the same issue, when i hit the "Exit Tina" Button. 

`Uncaught TypeError: f.current is null`

**Comment by lautapercuspain** [comment]
> How is it impacting Tina installation? I can't reproduce it on https://tina.io/, I was wondering If this was just something specific to the demo that isn't open to public changes.

This is not happening in https://tina.io/, this is reproducible in standalone installations of the Tina CMS package.

**Comment by mbrain-io** [comment]
> How is it impacting Tina installation? I can't reproduce it on https://tina.io/, I was wondering If this was just something specific to the demo that isn't open to public changes.

@DirtyF This happens on basic GitHub workflow:

https://user-images.githubusercontent.com/86771348/124573311-b6748300-de49-11eb-979c-33bf78f6bdc8.mov

**Comment by DirtyF** [comment]
@mbrain-io Could you share more context? What steps did you take to get into this error? What is your setup?

**Comment by mbrain-io** [comment]
> @mbrain-io Could you share more context? What steps did you take to get into this error? What is your setup?

Sure, I just followed [GitHub Backend tutorial](https://tina.io/guides/nextjs/github/initial-setup/), here is the resulting [repo](https://github.com/mbrain-io/test-tina-github).

Things I did differently then tutorial:
- Used .env.local instead of .env
- Downgraded all Tina packages to 0.41.1 because of [this](https://github.com/tinacms/tinacms/issues/1865)
