### ISSUE TITLE
react-tinacms-editor: link not saved when using keyboard shortcut

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#1856]
Given I'm editing content in the WYSIWYG on https://tina.io
When I try to create a link with `CTRL-K`
Then the URL field is not focused
Then the link is not added to the Markdown source

It works if I use the link button in the toolbar.

**Demo**: https://www.loom.com/share/88e460926044443b8c7752798470ccd8

**Comment by Nrestrepo05** [comment]
Hey! I could reproduce it. I'd like to work on this issue

**Comment by DirtyF** [comment]
@Nrestrepo05 Thanks that'd be very helpful!

**Comment by Nrestrepo05** [comment]
Hello! I have this question. If someone could answer it would be great!

https://community.tinacms.org/t/developing-cycle/599

**Comment by Nrestrepo05** [comment]
Hey! I've been researching, and I think I know where this is happening, but I still can't find why. Here I'll tell you what I found:

(all this is in packages/react-tinacms-editor/src)

- /plugins/Link/Popups/Form.tsx line: 55
  
  view.state.selection.$anchor is different when we use the button and when we use the shortcut. This is the main issue. I find that this is happening here:

- /plugins/Link/Popups/InnerForm.tsx line: 50

  when we use the shortcut, the input is focused and it changes the activeElement of the browser, you can see it on /src/components/ProsemirrorEditor/index.tsx line 66. If we use the button, the input is focused but the activeElement does not change.

The problem is that when we want to save the link we are passing the selection position of the input, but this is only happening when we use the shortcut.

I think that I can fix this way much faster if you know some way of setting a debugger. I can see the stack trace I can figure out why this is happening.

thanks!
