### ISSUE TITLE
Cannot create styled-component for component: undefined

### ISSUE THREAD

**Issue by mbrain-io** [tinacms/tinacms#1865]
## Description

By just following [GitHub Backend](https://tina.io/guides/nextjs/github/initial-setup/) tutorial, it produces this error:

```
Cannot create styled-component for component: undefined
```

### Steps to reproduce

Here is the [GitHub project](https://github.com/mbrain-io/test-tina-github/tree/buggy). Its basically what you get when you follow "GitHub" backend tutorial.

These are important dependancies:

```
"next": "11.0.1",
"react": "17.0.2",
"react-dom": "17.0.2",
"tinacms": "^0.42.1",
"react-tinacms-github": "^0.42.1",
"next-tinacms-github": "^0.42.1",
"sass": "^1.35.1",
"styled-components": "^5.3.0"
```

#### Tinacms Package Versions

```text
├── UNMET PEER DEPENDENCY @tinacms/core@^0.29.0
├── UNMET PEER DEPENDENCY @tinacms/fields@^0.29.0
├── next-tinacms-github@0.42.1
├── react-tinacms-github@0.42.1
├── tinacms@0.42.1
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |     Safari    |
| os      |    Mac     |
| node    |    v14.15.1     |
| npm     |    6.14.8     |

**Comment by mbrain-io** [comment]
Btw, if I downgrade dependencies error message disappears:

```
"dependencies": {
    "next": "^10.1.2",
    "next-tinacms-github": "^0.39.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-tinacms-github": "^0.39.0",
    "sass": "^1.35.1",
    "styled-components": "^4.4.1",
    "tinacms": "^0.39.0"
  },
```

**Comment by eddyojb88** [comment]
I second this problem. Been trying to solve it for 2 whole evenings, naturally thinking the problem was me. Thank you for raising @mbrain-io

**Comment by eddyojb88** [comment]
Ahh dude, thank you.

I have been racking my brains with the Tina-Strapi tutorial. I understand the logic of asking the user to follow the tutorial to learn but it cost me so much unnecessary time as a beginner combing through the code thinking I did something wrong.

To the maintainers, is it OK if we had a base beginner **working** example stored in GitHub for all users?

**Comment by FREEZX** [comment]
Same issue here. @eddyojb88 @mbrain-io found any solutions beside reverting back to 0.41.1?

**Comment by coreyaus** [comment]
I've also had the same issue when trying to upgrade to TinaCMS `v0.42.1`. It's also present when trying to upgrade to `0.43.0-alpha.1` (which is now the latest version)

In my case it looks like the error is thrown by the `react-tinacms-inline` package, which is only needed in my project as it's required by the `react-tinacms-editor` package (not sure how that compares with the tutorials you others are following).

I was able to temporarily workaround the issue but still upgrade to the latest version of `tinacms` by commenting out the following line in my code (which I previously passed as an option within `new TinaCMS`):
```
plugins: [MarkdownFieldPlugin],
```

There are a few ways to [add plugins](https://tina.io/docs/plugins/#adding-plugins) so something similar might appear in those other tutorials as `cms.plugins.add(MarkdownFieldPlugin)` or `usePlugins([MarkdownFieldPlugin])`. The `HtmlFieldPlugin` also seems to throw the same error.

Obviously this is not a proper fix but might at least allow you to complete the tutorials, just with plain textarea fields rather than HTML/markdown content editors. Hope that helps someone, and that it's possible to resolve the underlying issue soon.

**Comment by coreyaus** [comment]
I'm also seeing a potentially related error on my project, which uses Tina Cloud. When using the `createCloudClient` method and completing the authentication process the user is initially redirected to an error page with the following message:

> **Unhandled Runtime Error**
> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> Check the render method of `AsyncButton`.

When refreshing the page everything works as expected. That is, the error only appears when landing back on an admin page straight after the authentication process is complete. A full page reload will render everything as expected.

This may be unrelated but I'm including here in case it hints at a possible cause or potential fix to someone more familiar with the internals of the project (i.e. perhaps this relates to the render method of the `AsyncButton` component?)

**Comment by ACoolTurtle** [comment]
I am seeing this same error, on version 0.43.0, it is definitely related to the plugin, but I'm not sure what is causing the issue internally

**Comment by Enigmatical** [comment]
We have an update going out to the `react-tinacms-github` package (0.43.1) that fixes a breaking issue I encountered when stepping through the [GitHub Backend](https://tina.io/guides/nextjs/github/initial-setup/) tutorial.  

While I was not able to recreate the issue here:
```Cannot create styled-component for component: undefined```
I actually encountered a more troubling error where the `cms` instance was not being found:
```Error: useCMS could not find an instance of CMS```

Once 0.43.1 is out, I am curious if this also solves the `styled-component` problem.  If it doesn't, could someone provide the steps to recreate it using 0.43.1?  I progressed through the GitHub Backend tutorial through this step:

https://tina.io/guides/nextjs/github/custom-doc-styled-components/

and suspected it might trigger it.

**Comment by coreyaus** [comment]
Thanks @Enigmatical!

Appreciate your work on this one so far! I've added version `0.43.0-alpha.1` to my project but am still seeing the error from `styled-component`. You can see my steps to reproduce the simplest possible case in this demo repository: https://github.com/coreyaus/tinacms-issue-1865/commits/main. The commit history will walk you through the changes pretty clearly but the main steps were:

1. `yarn create next-app --typescript`
    > What is your project named?
    > tinacms-issue-1865

2. `cd tinacms-issue-1865 && npx tina-graphql-gateway-cli init`
    > do you want us to override your _app.js?
    > yes
    - I also had to manually delete the `_app.tsx` file (it seems the tina `init` command doesn't do this automatically given we're using TypeScript)

3. `yarn add react-tinacms-editor react-tinacms-inline`
    - Also update the `tina-wrapper.tsx` file to pass `cms` instance to `<TinaCloudProvider>`
    - Change the name of the first post from `HelloWorld.md` to `helloworld.md` (this was necessary to avoid 404 errors at http://localhost:3000/demo/blog/helloworld in my dev environment)

4. Import `MarkdownFieldPlugin` from `"react-tinacms-editor"` package and add to the `cms` instance in the `tina-wrapper.tsx` file
    - At this point if you run `yarn tina-dev` and access the first post at http://localhost:3000/demo/blog/helloworld you will see the following error:
        > Cannot create styled-component for component: undefined

Thanks again for looking into this one!

**Comment by Enigmatical** [comment]
This is perfect, @coreyaus 👍 

Turns out it was pretty simple to recreate, so I'll start chasing this.  Hope to have an update (or at least an idea) sometime today.

**Comment by Enigmatical** [comment]
Hopefully good news :) I've identified another dependency issue that appears to fix the `styled-component` problem:
https://github.com/tinacms/tinacms/pull/1875

It has been released on the `next` channel, so you can use:

```
npm install react-tinacms-inline@next react-tinacms-editor@next

-or-

yarn add react-tinacms-inline@next react-tinacms-editor@next
```

Crossing my fingers that this takes care of the problems listed here 👍 
If it does, we'll make the fix part of the next release.

**Comment by ACoolTurtle** [comment]
@Enigmatical It worked as far as I no longer get the above specified error, however it is still erroring out on creating a styled component. 

```console
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `AsyncButton`.

```

**Comment by coreyaus** [comment]
Thanks for the update Chris! It's now working for my use case with the local client 👌  

**`createLocalClient()`** 🎉 

I've pushed a commit to the example repo above with the `next` version of those packages and the markdown editor now works as expected, with no complaints from the `react-tinacms-inline` package **as long as I'm using the localClient**: https://github.com/coreyaus/tinacms-issue-1865/commit/62b60c0b3532289613feb96547b4035427022747

**`createCloudClient()`** 🤔 

- Steps to recreate:
    - As a follow up to see what @ACoolTurtle was referring to, I've pushed the following commit to introduce the `createCloudClient()` option to the repository: https://github.com/coreyaus/tinacms-issue-1865/commit/1d1ecce7260a543b7a8f9555181f5d2c2a78bfb6. If you run that locally with the following values in an `.env.local` file you'll run into the behaviour described below:
        ```
        NEXT_PUBLIC_USE_LOCAL_CLIENT=1
        NEXT_PUBLIC_ORGANIZATION_NAME=***
        NEXT_PUBLIC_TINA_CLIENT_ID=***
        NEXT_PUBLIC_EDIT_BRACH=main
        ```

- Specific errors we're seeing:
    - With that setup, you'll see the authentication prompt from TinaCloud. After completing the authentication process you'll see an error page with that error message pasted above:
        > Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined
    - After refreshing the page that error will go away but there will be an error in the JS console and while the Tina sidebar will load, it won't be populated with any forms (i.e. it will show the default placeholder).

My example repo doesn't use any inline editing features directly - it only needs `react-tinacms-inline` given it's required by `react-tinacms-editor` in order to use the `MarkdownFieldPlugin`. @ACoolTurtle - are you using more advanced inline editing features to see the error you pasted above, or is it likely just because you're also using the cloud client as outlined here?

Cheers team!

**Comment by ACoolTurtle** [comment]
@coreyaus Yah its just using the cloud component for me

**Comment by Enigmatical** [comment]
More, hopefully, good news :)

I believe I've found the issue with the render method of the `AsyncButton` and I've merged the fix:
https://github.com/tinacms/tina-graphql-gateway/pull/355

The fix is up on the `beta` channel for `tina-graphql-gateway`.

**Comment by FREEZX** [comment]
> We have an update going out to the `react-tinacms-github` package (0.43.1) that fixes a breaking issue I encountered when stepping through the [GitHub Backend](https://tina.io/guides/nextjs/github/initial-setup/) tutorial.
> 
> While I was not able to recreate the issue here:
> `Cannot create styled-component for component: undefined`
> I actually encountered a more troubling error where the `cms` instance was not being found:
> `Error: useCMS could not find an instance of CMS`
> 
> Once 0.43.1 is out, I am curious if this also solves the `styled-component` problem. If it doesn't, could someone provide the steps to recreate it using 0.43.1?
> 
> I progressed through the GitHub Backend tutorial through this step:
> 
> https://tina.io/guides/nextjs/github/custom-doc-styled-components/
> 
> and suspected it might trigger it and found it did not.

I'm encountering the same `useCMS could not find an instance of CMS` issue, I installed the latest versions I could find on all tina packages in my project:

```
    "@tinacms/icons": "^0.42.1",
    "@tinacms/react-core": "^0.43.0-alpha.1",
    "@tinacms/react-forms": "^0.43.3",
    "@tinacms/react-modals": "^0.43.0",
    "@tinacms/styles": "^0.42.1",
    "react-tinacms-editor": "^0.43.2-alpha.0",
    "react-tinacms-inline": "^0.43.2-alpha.0",
    "react-tinacms-strapi": "^0.43.0-alpha.1",
    "tinacms": "^0.43.0-alpha.1",
```

Any idea how to solve this? My project worked perfectly on the older versions of these packages.

**Comment by mbrain-io** [comment]
Just to report that original issue I submitted:

"Cannot create styled-component for component: undefined"

Is solved with the latest packages:

```
"tinacms": "^0.43.3"
"react-tinacms-github": "^0.43.3",
"next-tinacms-github": "^0.43.3",
```

Thank you guys!
