### ISSUE TITLE
Investigate the versioning PR and how to get it to run CI

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#1959]

**Comment by dwalkr** [comment]
https://github.com/tinacms/tinacms/pull/1961 was a lazy attempt to fix this but didn't work

The section on "triggering further workflow runs" here explains the problem: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs

I think `changesets/action` is using `create-pull-request` under the hood so much of that troubleshooting info is relevant. Giving a different `GITHUB_TOKEN` to the job that uses `changesets/action` should be enough to trigger `pull_request` workflows, but how we go about doing that might warrant some discussion. Currently, the versioning PRs have to be merged by a repository admin because the required checks don't run - this doesn't seem like a horrible limitation if the alternative requires managing Personal Access Tokens.

Putting this on the back burner as it isn't an outright blocker for now.

**Comment by jeffsee55** [comment]
May be able to be run via the `workflow_dispatch` action (https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow)
