### ISSUE TITLE
Support Forestry's Document Section

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#1982]
See [docs](https://forestry.io/docs/editing/data-files/)

Right now the GraphQL API doesn't support Forestry's concept of data files, which are single`.yml`/`.json`/`.toml` files that can be edited and referenced in other sections.

There are 2 additional features I've discussed with Jordan which would simplify our schema configuration: 
1. Data files which start with an array are invalid, meaning the top-level element in the file must be an object
1. Enforce that each Document is backed by 1 FMT definition. This prevents us from having to infer the type of the document in our graphQL schema generation.

While it may be the case that we don't bring in all of Forestry's existing features, this one seems really powerful and is something I myself have reached for a lot.

**Comment by major-mayer** [comment]
Can we maybe reopen this issue or is there a reason why it's a "wontfix"?

**Comment by jamespohalloran** [comment]
Update on this since it's a rather old ticket.
This is mostly supported now thanks to a few updates.
- These data types are all supported by a collection: .yml/.json/.toml
- Collections can have the functionality of a "single document collection" by defining its `ui.allowedActions` https://tina.io/docs/editing/single-document-collections/

**Comment by major-mayer** [comment]
I don't really think that this issue is completed already.
Lets take for example a document file/ section like this, which was perfectly valid in Forestry:
```yaml
---
- id: nav_button
  translation: Kontakt
- id: service_subtitle
  translation: Entdecken Sie
- id: service_title
  translation: Unsere Angebote
- id: project_subtitle
  translation: Unsere Arbeit
- id: project_title
  translation: Neuste Projekte
```

How should i configure Tine to use this top document file if it contains a top-level list?
I tried it with something like this:
```ts
{
        format: "yaml",
        label: "Übersetzungsdateien",
        name: "uebersetzungsdateien",
        path: "i18n",
        frontmatterFormat: "yaml",
        match: {
          include: "**/*",
        },
        ui: {
          allowedActions: {
            create: false,
            delete: false,
          },
        },
        fields: []
      },
``` 

But Tina is complaining about the missing fields:
```
Error Array must contain at least 1 element(s) at path collections.17.fields 
```

Somewhat understandable, but then I wouldn't consider this issue to be completed (because it doesn't fully support document sections) until this feature request is also implemented: https://github.com/tinacms/tinacms/discussions/4243
For reference: https://web.archive.org/web/20220403071947/https://forestry.io/docs/editing/data-files/
