### ISSUE TITLE
getStaticPropsForTina complicates setup

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2108]
getStaticPropsForTina to me feels a bit unnecessary. Its role seems to be to make a request to the local API, as well as returning some of the arguments that were passed in.

Our current starter code:
```
export const getStaticProps = async ({ params }) => {
  const tinaProps = (await getStaticPropsForTina({
    query: `#graphql
      query BlogPostQuery($relativePath: String!) {
          // ...
      }
    `,
    variables: { relativePath: `${params.filename}.md` },
  })) as { data: { getPostsDocument: PostsDocument } };

  return {
    props: {
      ...tinaProps,
    },
  };
};
```

This to me feels a bit more clear about what getStaticProps is actually doing/returning:
```
export const getStaticProps = async ({ params }) => {

  const postRequestArgs = {
    query: `#graphql
      query BlogPostQuery($relativePath: String!) {
         // ...
      }
    `,
    variables: { relativePath: `${params.filename}.md` }
  }

  const post = new LocalClient().request(postRequestArgs)

  return {
    props: {
      post, // use this on your production page
      tinaArgs: postRequestArgs // needed for the Tina wrapper to re-request draft content client-side
    },
  };
})
```

The proposed solution also wraps all the tina stuff that gets sent to the frontend in a "tinaArgs" object, so it's clear what's for the production site, and what's for the frontend `TinaCMS`component. 

Thoughts?

**Comment by jamespohalloran** [comment]
Also, it demonstrates that there's nothing Next-specific going on here. This proposed snippet could be run anywhere (alongside the graphql server)

**Comment by jeffsee55** [comment]
In your example, we'd need some way of knowing that `post` was part of our live data, and I'm not sure this API is more clear. At least with `getStaticPropsForTina` there's an explicit nature to it so the user can just rely on us rather than worry about `LocalClient` and if they're composing things properly. Curious to hear more input on where the problems are.

**Comment by jamespohalloran** [comment]
`post` could be remapped to `data` within the client-side <TinaCMS> provider. If you were using a catchall `TinaCMS` provider in a `_app.tsx`, you may want to call this variable `data` instead, but I don't think that affects my point about getStaticPropsForTina.

> There is something Next-specific here, this wouldn't work in any non-SSG build context

If I understand correctly, `getStaticPropsForTina` does 2 things:
- Request content from a `LocalClient`
- Format a response with the graphql response, and the passed in arguments.

In your example, you're right that it's SSG-specific because under the hood it's using a static-only client that can't be configured. Since we've broken up the two responsibilities in my example, it's no longer next-specific, (as long as you're hitting an available server at the time of request).

**Comment by jeffsee55** [comment]
> post could be remapped to data within the client-side provider 

We'd need a way to tell it to do that, what would it look like in your mind?

**Comment by jeffsee55** [comment]
> It's just a variable name. As I mentioned, if the user is using a catchall TinaCMS provider in _app, this may in fact more sense to call this "data".

Ok, yeah `data` is intentionally generic, since this same logic will flow from every `getStaticProps` request in your app. And that sort of leads back to why this function is nice, there's really no way for users to mess it up. 

Another thing this function does is [fail silently](https://github.com/tinacms/tinacms/blob/main/packages/tinacms/src/tina-cms.tsx#L317) on purpose. That's intentional since when you create a new document, it's `path` hasn't been built yet. So we need to allow the query to fail and then hydrate it client-side. With your proposal we'd need to make the user do that

**Comment by jamespohalloran** [comment]
> Another thing this function does is fail silently. That's intentional since when you create a new document, it's path hasn't been built yet. So we need to allow the query to fail and then hydrate it client-side. With your proposal we'd need to make the user do that

I don't think I understand. By the time `getStaticProps` is run after creating a new document (on the next build), wouldn't the document exist?

**Comment by jeffsee55** [comment]
> after creating a new document (on the next build)

The Next build is running, but there's a solid minute there where the newly created page exists in Github but not in the build. So we pass `fallback: 'blocking'` from `getStaticPaths` which tells Next.js to render this page (which means it'll call `getStaticProps` at runtime). And since we don't have a server running locally the API call will fail (silently, thanks to `getStaticPropsForTina`), and we'll then show a [404 message briefly while we rehydrate it client-side](https://github.com/tinacms/tina-cloud-starter/blob/main/pages/posts/%5Bfilename%5D.tsx#L11-L17) since we get that data from Github.

**Comment by jamespohalloran** [comment]
Ah ok. 
Well another option could be to extend the `LocalClient` as a `StaticClient`? We can override the `request` function and have it swallow those errors. 

```
export const getStaticProps = async ({ params }) => {

  const postRequestArgs = {
    query: `#graphql
      query BlogPostQuery($relativePath: String!) {
         // ...
      }
    `,
    variables: { relativePath: `${params.filename}.md` }
  }

  const data = new StaticClient().request(postRequestArgs)

  return {
    props: {
      data, // use this on your production page
      tinaArgs: postRequestArgs // needed for the Tina wrapper to re-request draft content client-side
    },
  };
})
```

Client/LocalClient has some logic that mixes concerns with both frontend / backend implementations anyways (e.g references to localStorage). Might not be such a bad idea to have separate frontend/backend implementations, rather than our current LocalClient which is used in both scenarios, but for different roles.

**Comment by perkinsjr** [comment]
Conceptually the getStaticPropsForTina was/is a good idea, however, simplifying the and unwrapping it will allow :

- Less dependent on Next overall 
- Easy to extend 
- Give clarity about where and when certain things can be used. 

Which IMO leans towards less friction for DX which is overall the most important factor.

**Comment by jeffsee55** [comment]
I'm cool with this, but should we actually _remove_ it? We can mark it as deprecated for now

**Comment by perkinsjr** [comment]
We should deprecate over remove. We don't want to make breaking changes.

**Comment by jamespohalloran** [comment]
Made this PR ready for review: https://github.com/tinacms/tinacms.org/pull/1063

**Comment by jamespohalloran** [comment]
getStaticProps for Tina has been removed from the docs, so I think the only remaining things here are to:

- [ ] Remove it from the originalstarter https://github.com/tinacms/tina-cloud-starter/tree/main
- [ ] Tag it as deprecated in the code.

**Comment by kldavis4** [comment]
@jamespohalloran not sure if this is another remaining item, but I think the cli init is using getStaticPropsForTina in the generated `demo/blog/[filename].js`

**Comment by jamespohalloran** [comment]
Ah good catch, @jeffsee55 let me know if you want me to jump in and make a PR for either of those last items

**Comment by jeffsee55** [comment]
The SDK is also generating this, so we'll want to remove that as well.
