### ISSUE TITLE
Adding a document with default data

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#2231]
### Discussed in https://github.com/tinacms/tinacms/discussions/2230

<div type='discussions-op-text'>

<sup>Originally posted by **tbenbow** November 11, 2021</sup>
How should I define default data when creating a new document with the "Add Document" modal?

I tried using the defaultItem property in my template but my new markdown document for my post only has a single property "_template: post" - it doesn't add the defaultItem data I define.

Here is my schema...
```
export default defineSchema({
  collections: [
    {
      label: "Posts",
      name: "posts",
      path: "content/posts",
      templates: [ post ]
    },
  ],
});
```

And here is the post template I am importing...
```
export const post: TinaTemplate = {
    name: "post",
    label: "Post",
    ui: {
      defaultItem: {
        title: "The Title",
      },
    },
    fields: [
      {
        type: "string",
        label: "Title",
        name: "title", 
      }
    ]
}
```</div>

**Comment by jeffsee55** [comment]
For collections with multiple templates will need to include the `_template` key:

```
              ui: {
                defaultItem: {
                  posts: [
                    {
                      _template: "blog_post",
                      image: "http://placehold.it/300x200",
                      title: "Hello, World",
                      desc: "Lorem ipsum dolor sit amet, ",
                    },
                  ],
                },
              },
```

**Comment by jeffsee55** [comment]
Still relevant

**Comment by jamespohalloran** [comment]
Now that adding documents has been moved from the contextual editing view, to the "CMS" view, is this still important to users? (I'm not aware of this type of functionality in other CMS'). If they want to create a page with some prefilled content, they might instead just duplicate an existing page.

Previously, it was a hard requirement for us, (because the contextual page-preview would blow up without any required fields).
