### ISSUE TITLE
Can't access functionality when editing long form content with the MDX editor 

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#2284]
For example when editing a very long content, somehow to make a text bold, I need to scroll back all the way up to select bold. (Maybe either make the styling fixed or add shortcut like Ctrl + B for bold and similarly for other styling as well like underline, italic.

cc @jeffsee55 @spbyrne 

[Originally posted on discord](https://discord.com/channels/835168149439643678/848932514911354880/913847120887439401) (feel free to [join](https://discord.com/invite/zumN63Ybpf))

**Comment by jeffsee55** [comment]
I had originally done a floating toolbar like what we have in the markdown inline editor but the MDX dropdown button was too much UI to put in there on a narrow sidebar. I also had a few different designs that use the [balloon toolbar](https://plate.udecode.io/docs/components/balloon-toolbar), which would free up some real estate in the toolbar since bold, italic, etc wouldn't need to be in there
<img width="226" alt="Screen Shot 2021-11-29 at 8 51 25 AM" src="https://user-images.githubusercontent.com/5414297/143909709-5bf4a39e-c149-4f99-8c86-6e3f8c2d19a5.png">

**Comment by logan-anderson** [comment]
@jeffsee55 could we make the menu stick to the top of the page?

**Comment by jeffsee55** [comment]
@logan-anderson that's what I meant by "floating toolbar", though that sounds like the same thing as "balloon toolbar"... Yeah I had removed it because of the embed button but per discord discussion I think we'll make that embed button just part of the toolbar icons and make it sticky.
