### ISSUE TITLE
Tina + Tailwind punchlist

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#2353]
Won't fix (old APIs which haven't been supported since 0.43)
- Toolbar
- Inline editing

---

Will fix (based off the `tina-cloud-starter`)
- ~~Merge latest `main` and catch up `inject-tailwind` branch~~
- ~~Media Manager (general styles, button placement, scroll bar placement)~~
- ~~TagsField~~
- ~~ToggleField (click target was too small)~~
- ~~ModalActions (Content Creator)~~
- [x] ColorField (untested) - @Enigmatical 
- [x] NumberField - @Enigmatical "Looks good; using the built-in `number` with `InputField` styles 👍 "
- [x] RadioGroupField - @Enigmatical
- [x] CheckboxGroupField - @Enigmatical 
- [x] BranchSwitcher - @Enigmatical 
- [x] `examples/basic` - @Enigmatical
- [x] `LocalWarning` does not fit well with the new `Sidebar` styles - @spbyrne

**Comment by Enigmatical** [comment]
`ColorField` looks good 👍 
<img width="403" alt="Screen Shot 2021-12-15 at 3 58 04 PM" src="https://user-images.githubusercontent.com/1699544/146271515-b7fda128-4b2e-4a93-8b80-375e6c2714e4.png">

**Comment by Enigmatical** [comment]
`RadioGroup` is unchanged in the new branch 👍 
<img width="441" alt="Screen Shot 2021-12-15 at 4 10 27 PM" src="https://user-images.githubusercontent.com/1699544/146272968-725f443f-dbda-42d1-b7f0-45fa638c8b4f.png">

**Comment by Enigmatical** [comment]
`CheckboxGroupField` had a couple of icon issues, easily fixed with the same changes we've been making 👍 
<img width="341" alt="Screen Shot 2021-12-15 at 4 20 21 PM" src="https://user-images.githubusercontent.com/1699544/146275358-ee985630-b0d2-4c48-a336-7f7141134e6f.png">

**Comment by Enigmatical** [comment]
`BranchSwitcher` looks the same with `tailwind`, mainly because it is leveraging a combination of `inline` styles and `styled-component`s.
<img width="473" alt="Screen Shot 2021-12-16 at 3 05 36 PM" src="https://user-images.githubusercontent.com/1699544/146449137-bfd136fb-78dc-4bc3-879b-c87220823f9e.png">

**Comment by Enigmatical** [comment]
On the `examples/basic`, I ran into an interesting problem where the `Sidebar` (despite being hidden) was preventing me from clicking through to the `Home` and `Posts` links on the body.  When the `Sidebar` was opened, I could click those links just fine.

I discovered that the `style` on the inner `div` had baked in `width` and `max-width` that was causing the parent `div` to overlay across the content:
<img width="448" alt="Screen Shot 2021-12-16 at 3 58 59 PM" src="https://user-images.githubusercontent.com/1699544/146455274-e85a5584-9cb1-433c-8751-d91587bb8960.png">

The fix is to leverage the `displayState` and switch the `style` of that inner `div` to `{ width: 0 }` when the `Sidebar` is closed:
<img width="385" alt="Screen Shot 2021-12-16 at 4 01 13 PM" src="https://user-images.githubusercontent.com/1699544/146455490-fa7c9216-b7bc-4de0-a1b6-1c746efdbb31.png">

**Comment by spbyrne** [comment]
There's been a bug where the sidebar contents are resizing in width while the sidebar slides in/out, I think if I fix that and use `pointer-events` I can solve both issues. I may end up reverting the above fix if that's true, but otherwise that fixes the issue as well.

**Comment by jeffsee55** [comment]
- [ ] `style.css` sets `font-family` for the `body`, it should be scoped to Tina only

**Comment by spbyrne** [comment]
I'll just remove that, it's no longer needed given Tailwind's base styles.

**Comment by Enigmatical** [comment]
[ ] Check `tina-tailwind` styles against Multiple Forms interface.

**Comment by Enigmatical** [comment]
> * [x]  Check `tina-tailwind` styles against Multiple Forms interface.

While **Multiple Forms** is a bit of an edge case, the UI looks fine:
![Screen Shot 2022-01-10 at 15 17 04](https://user-images.githubusercontent.com/1699544/148840785-ab0ae634-aeb6-4901-8765-2ea25f834bb2.png)

**Comment by Enigmatical** [comment]
Closing this issue now that https://github.com/tinacms/tinacms/pull/2261 has been merged.  Future issues will be open in their own cards.
