### ISSUE TITLE
Can react-tinacms-editor and other external field packages be apart of main package?

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2410]
## Summary

There's a bit of extra setup in using certain fields, which are not apart of the main tinacms package. 

E.g, [markdownPlugin](https://tina.io/docs/reference/toolkit/fields/markdown/), [htmlPlugin](https://tina.io/docs/reference/toolkit/fields/html/) (I'm not sure if this plugin is still used), ~~and [date plugin](https://tina.io/docs/reference/toolkit/fields/date/).~~

Now that we have a pattern for dynamically loading tina, does it matter if these packages are part of the main package? 

### Motivation

The Markdown is very common, and the extra package / plugin-registration increases up-front complexity. 

If we can make this change, we'll also need to:

- [ ] Update starters
- [ ] Test that if users are manually registering the markdown plugin, things don't break (or we'll need to publish a breaking change)
- [ ] Update docs
- [ ] Update CLI init?

**Comment by Enigmatical** [comment]
`DateField` is actually part of the default plugins:
https://github.com/tinacms/tinacms/pull/1807

We have had an ongoing discussion about the MarkdownPlugin, though.  At one point, we felt it was a good candidate for training the user how to add additional fields (using the plugin system).  Might be worthwhile to open that discussion again.

**Comment by jamespohalloran** [comment]
> We have had an ongoing discussion about the MarkdownPlugin, though. At one point, we felt it was a good candidate for training the user how to add additional fields (using the plugin system). Might be worthwhile to open that discussion again.

I think that's a fair point, but I wonder if another field type would be a better candidate (e.g registered the color field, or some field component that's outside of a fields its default behavior). The markdown plugin is a bit awkward, because when a string has the "isBody" property, we already sort of assume it's markdown content (we know it's a .md file).

**Comment by jeffsee55** [comment]
I agree that something like the color field would be just as good of a teaching point. Now that we have a rich-text editor baked in, We have a couple options:
1. Get our new (Slate) editor to support parsing markdown into a Slate-friendly AST. This is currently done in `@tinacms/graphql` on the server (as this is a better place for markdown parsing to happen), but some portions of that would need to be run in the browser if we do that. (We can't use the `markdown-it` parser because the shapes wouldn't be compatible). I'm somewhat leery of getting the remark parser to work in the browser, though I suppose it probably will work if we can omit the MDX portions.
2. Pull the markdown editor back into core, and offer it as a custom component (`component: "markdown"`). This is far simpler, but we'll need to continue to support 2 rich text editors until we figure something out. And the prosemirror one has bugs that I'm not sure we intend to fix (table support).

**Comment by jeffsee55** [comment]
Not stale
