### ISSUE TITLE
Slow CI publish actions

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2491]
When we merge to main, it takes a long time to run the publish actions 
E.g, this merge one took 41 minutes: https://github.com/tinacms/tinacms/actions/runs/1747183504

The `install dependencies` step seems to be the biggest culpret (at ~15 minutes). Can we bring that down?

Also, we run the script twice, under a dev tag and latest tag. Can we conbine those actions, so that we only need to install once?

**Comment by jeffsee55** [comment]
> The install dependencies step seems to be the biggest culpret (at ~15 minutes). Can we bring that down?

Since we have our dependencies in source control we use this is a [security measure](https://yarnpkg.com/cli/install) to make sure the dependencies all match their checksum. The solution here would be to stop caching dependencies (aka - get rid of Yarn's zero-installs feature), I would be cool with this change. It'd make PRs much smaller in a lot of cases too.
