### ISSUE TITLE
How should `defaultValue` behave?

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#2706]
A few statements about default behavior that we may want to pin down so we know how we'd like to proceed as the extending Tina work progresses.

### When in edit-mode, null values are replaced with their default items*

*not working yet, but will - would like to get an idea for expectations before implementing.

This is currently considered a feature, but I'm not sure it's what we want. As an editor, you may land on a page and see exactly what you want (because the developer set up good default values. So you don't save anything or really do anything, and you never exit edit-mode. At that point, when your work goes to production there will be a missing value.

### Outermost `defaultValue` wins

```ts
defineSchema({
  collections: [
    {
      label: 'Block Page',
      name: 'blockPage',
      format: 'mdx',
      path: 'content/block-pages',
      fields: [
        {
          label: 'Blocks',
          name: 'blocks',
          type: 'object',
          list: true,
          ui: {
            defaultValue: [{
              _template: 'hero',
              title: "hello #1"
            }]
          },
          templates: [
            {
              name: 'hero',
              label: 'Hero',
              ui: {
                defaultValue: {
                  title: 'hello #2',
                },
              },
              fields: [
                {
                  label: 'Title',
                  name: 'title',
                  type: 'string',
                },
                {
                  label: 'Description',
                  name: 'description',
                  type: 'string',
                },
              ],
            },
          ],
        },
      ],
    },
  ],
})
```

The value will be:

```js
[{
  _template: 'hero',
  title: "hello #1"
}]
```
Instead of 
```js
[{
  _template: 'hero',
  title: "hello #2"
}]
```

What _should_ the behavior be is open for interpretation, though some have mentioned this feels wrong and the most-specific property should win.

### Similarly, `defaultItem` on a list object ignores child default values

What is the expected behavior here?

### `defaultValue` is not used if an adjacent field is present

_AKA - we don't merge real/default values._

If I have a `title` field and a `description` field. 

```
{
  label: 'Title',
  name: 'title',
  type: 'string',
  ui: {
    defaultValue: 'Some title',
  },
},
{
  label: 'Description',
  name: 'description',
  type: 'string',
  ui: {
    defaultValue: 'Some description',
  },
},
```
And a document with only the `title`:

```md
---
title: "Hello, World"
---
```
The `form.values` will be `{title: "Hello, World"}`

**Comment by Stephen8787** [comment]
Stegg

**Comment by jamespohalloran** [comment]
The way that I would expect default values to work, is that they would be applied when adding a new piece of content, (and those defaults would be persisted if I saved without changing them.) 

If this was the case, you wouldn't have to worry about your last case..

> defaultValue is not used if an adjacent field is present
> AKA - we don't merge real/default values.

**Comment by jeffsee55** [comment]
`defaultItem` is what's relevant for new content as part of a list, `defaultValue` currently works for null fields upon initializing the form.

**Comment by llibdude** [comment]
>When in edit-mode, null values are replaced with their default items*

My main concern with default values i that they aren't being populated by `useTina`, bug filed here https://github.com/tinacms/tinacms/issues/2814.  I came to this ticket for that but I can try to chime in on the other topics as well.

>As an editor, you may land on a page and see exactly what you want (because the developer set up good default values. So you don't save anything or really do anything, and you never exit edit-mode. At that point, when your work goes to production there will be a missing value.`

This is a good point that I had not considered. I'm not sure how it works today, but in this case would the `Save` button be enabled? i.e. would Tina acknowledge the unsaved changes? If so that is one thing that can help.  Perhaps improving on the UX around the fact there are unsaved changes (I dont have any suggestions off the top of my head).  Lastly, if you have a dirty form and try to close the tab, it does yell at you that you have unsaved changes, that can help a bit as well UX-wise.

I'm also happy to pitch my idea for cloning from templates/other pages https://github.com/tinacms/tinacms/discussions/2675.  I think in the scenario where you are afraid of the above scenario, the proper workflow might be for that organization to create new pages from a template or clone.  In this way, if you are doing a hard copy of a file (with new filename), the file is saved already and any additional edits would feel natural when it comes to saving. (p.s. i really want templates/cloning 😃 )

> Outermost defaultValue wins

I'll admit, I don't have a strong opinion here.  I think a developer should just use one or the other, using both at the same time seems pointless to me?  I am more of a fan of setting defaults at the lower levels instead of the top because my schemas get deeply nested and I don't want to do the math when setting them at the root level.

> defaultValue is not used if an adjacent field is present
This seems like a bug to me.

**Comment by konsumer** [comment]
I would like to see `defaultValue` allow derived-fields, too.

Like this:

```js
import { defineSchema, defineConfig } from 'tinacms'
import slugify from 'slugify'

const schema = defineSchema({
  collections: [
    {
      label: 'Blog Posts',
      name: 'post',
      path: 'content/post',
      format: 'md',
      
      fields: [
        {
          type: 'string',
          label: 'Title',
          name: 'title',
        },
        {
          type: 'datetime',
          label: 'Date',
          name: 'date',
         
          // if no value is entered, use now
          defaultValue: values => new Date()
        },
        {
          type: 'rich-text',
          label: 'Blog Post Body',
          name: 'body',
          isBody: true
        },
        {
          type: 'string',
          label: 'URL Slug',
          name: 'slug',

          // get slug from title, if it's not set
          defaultValue: values => slugify(values.title, { lower: true, remove: /[*+~.()'"!:@]/g })
        },
      ],
    },
  ],
})
```

Additionally, if we had a `hidden` option, it could be a completely derived-field, and not show anything. I also think being able to derive the filename (and hide the input on new items) would be a very powerful combo:

```js
const schema = defineSchema({
  collections: [
    {
      filename: vals => {
        const d = new Date(vals.date).toLocaleDateString('en-US', { day: '2-digit', month: '2-digit', year: 'numeric' })
        return `${d}-${vals.slug}.md`
      }
    },
  ],
})
```

which combined with the other stuff would get the `slug` from `title`, the `date` from now, and make the filename match that. It could maybe just happen on a new file (so filenames don't change.)

**Comment by jamespohalloran** [comment]
I think my main questions on this discussion are:
- When is "defaultValue" applied?
- When is "defaultItem" on a list applied? 

I feel like using either property to replace your persisted values **at runtime** feels weird to me.
For example, if we have a nullable dateField. If the field has a defaultValue.. then it can never really be null because its value is always replaced at runtime.

I'd like to propose:
- `defaultValue` only being used when initially creating the new document with Tina. 
- `defaultItem` is only used when a new item is added to a list. 

If you want to set a fallback for a value (e.g, using `Date.now()` as a fallback if a date isn't set), then that could be handled in userland code.

**Comment by jamespohalloran** [comment]
Just chatted with @jeffsee55. He brought up the point that defaultValue can get weird when a objectField doesn't have a defaultValue, but it has a nested property with defaults.

We discussed the following:
- At the root, a collection would instead have a root-level "defaultItem". "DefaultValue" on a field would be deprecated. 
- The "defaultItem" value is only used when the document is created (or a defaultItem on a list field is only used when a list-item is created). There will be no runtime replacement of fields with their defaults. 
- Templates on a collection could each have their own "defaultItem".
- TBD: Maybe defaultItem is renamed to "default"?

So when a user clicks "New Document" on the below post collection...

```
  collections: [
    {
      // ...
      default: () => {
          return {
              title: 'my-post',
              tags: ["foo","bar"],
              created: new Date().toString()
          }
      },
      fields: [
        {
          name: 'title',
          type: 'string',
        },
        {
          name: 'created',
          type: 'datetime',
        },
        {
          name: 'tags',
          type: 'string',
          list: true,
          default: () => {
              return "blah"
          }
        },
    ]
 }]
```

They'd end up with:

```md
---
     title: 'my-post'
     tags: ["foo","bar"]
     created: //Today's date
---
```

When they add a list item and save...

```diff
---
-     tags: ["foo","bar"]
+     tags: ["foo","bar","blah"]
---
```

**Comment by NatoNathan** [comment]
The collection `default()` would need to accept a returned value with a `filename` property, and some input from the new document form.
```js
default: (formInput) => {
  return {
    fileName: formInput.name? slugify(formInput.name): uuidv4(),
    tags: [‘new’],
    title: formInput.name ?? ‘Untitled’,
    created: new Date().toString(),
  }
},
```

**Comment by jamespohalloran** [comment]
> @jamespohalloran
> 
> The collection `default()` would need to accept a returned value with a `filename` property, and some input from the new document form.
> 
> ```js
> default: (formInput) => {
>   return {
>     fileName: formInput.name? slugify(formInput.name): uuidv4(),
>     tags: [‘new’],
>     title: formInput.name ?? ‘Untitled’,
>     created: new Date().toString(),
>   }
> },
> ```

Hmm, I've been seeing defaults applied once as soon as you click "create document"

<img width="1443" alt="Screen Shot 2022-08-31 at 4 17 51 PM" src="https://user-images.githubusercontent.com/3323181/187764265-b0091ab2-f4da-4b5f-9867-57c63cdc292b.png">

but the filename would only be applied after you fill out the initial form with the full set of values (since it may depend on other fields). In this case, my gut feel is that it feels a bit weird to nest filename & the defaults together.

**Comment by NatoNathan** [comment]
In that case, it should be two separate functions although you could still set a default for the filename,
```js
default: () => {
  return {
    fileName”: uuidv4(),
    title: 'my-post',
    tags: ["foo","bar"],
    created: new Date().toString()
  };
} // or initialDefault,
onDocumentCreation: (values, document) => { // called after the new document form
  return {
    fileName: values.name? slugify : null, // null here would leave the filename unchanged
    tags: […document.tags, …values.tags],
  };
},
```

**Comment by jeffsee55** [comment]
To @NatoNathan's point, I wonder if we should just provide `isFilename` boolean for fields (like `isTitle`). In addition to that, we could expose the `form`'s values as part of the `format` callback so you could do this:

```ts
{
  name: 'post',
  path: 'content/posts',
  fields: [{
    name: 'filename',
    type: 'string',
    isFilename: true,
    ui: {
      format: (value, form) => {
        return mySlugifyFunction(form.values.title)
      }
    }
  },{
    name: 'title',
    type: 'string',
  }]
}
```

**Comment by jamespohalloran** [comment]
I think I'm just split on "filename" being grouped with fields. We wouldn't want it to get saved to the underlyings markdown/JSON, or show up in the sidebar UI, so it's behaviour feels pretty different to me.

**Comment by jeffsee55** [comment]
yeah it'd get special treatment, so maybe too confusing, but I think what we already have in `parse`/`format` could be exposed that would address most user's needs.

**Comment by NatoNathan** [comment]
The only note I will add is `format` being under `ui` it's not clear that it has effects beyond the UI. One could assume that `ui.format()` just formats for field for display purposes.

**Comment by konsumer** [comment]
I agree, but that is already true for other fields. However it works, I suggest it should match regular fields, so you don't have to do something funny on internal fields.
