### ISSUE TITLE
SPIKE: Data layer: Error when trying to get docs while still indexing

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#2791]
**Expected Deliverable**
Come up with a solution and review with the team

**Notes:**

Note: this all assumes the data layer is enabled.

## Description 

When I first create a tina-cloud app and I query the content right away I get an error from the server and do not get any content back. If I wait a min or two I can query the content. 

### Steps to reproduce

Create an example project and add a lot of content so the indexing takes a bit of time

### Expected result

I should get the content back or get an error saying that the content is still being indexed on the given branch

### Actual result

500 error from the server

**Comment by jamespohalloran** [comment]
For static builds that use the data layer, seems like this is a race condition (since the indexing would start at the same time as the build).

My understanding is that the backend might need a status endpoint, and the build should wait for the indexing to finish before building the site (either through a separate CI build step, or through a wrapper e.g: `"tinacms server:start -c \"next build\""`). Is that right? 
If so, should that work be apart of this ticket, or should we create a separate ticket?

**Comment by kldavis4** [comment]
Yes, I think a race might occur, especially if the schema was modified. I think a separate ticket probably is better.

**Comment by kldavis4** [comment]
Would be super useful for this to also track error status - when indexing has failed
