### ISSUE TITLE
Difficult to debug when using invalid branch with Tina 

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2917]
## Description

When you have the wrong branch set in Tina, it's difficult to debug why the "collections" view breaks in the CMS

https://www.loom.com/share/74129fcc0b3748d1ae47c641fa48ebc6

### Steps to reproduce

In .tina/schema.ts, change the branch to an invalid value. Run the site with yarn dev, and navigate to a collection 

### Expected result

- Suggestion 1: Use something like this as the default value (for all our starters, and for `tina init`):
```
const branch = process.env.NEXT_PUBLIC_TINA_BRANCH || process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_REF || process.env.BRANCH ||  "main";
```
- Suggestion 2: Clearer error, that links to an FAQ when a branch is invalid

### Actual result

Ambiguous error, that you can't click into when navigating to a collection in the CMS (See above loom)

#### Tinacms Package Versions

├── @tinacms/cli@0.60.17
└── tinacms@0.68.5

closes https://linear.app/tina/issue/ENG-123

**Comment by Enigmatical** [comment]
So it looks like the `internalClient` is swallowing up the more useful error and just responding with `statusText` from the `response` (hence why `Not Found` is shown).

If a file cannot be found or if the branch is invalid, the server responds with a `404` (which makes sense), but there's no way to know which has happened.

Right now, I've improved the `client` to use the `message` from the `response` if it exists:
<img width="1549" alt="Screen Shot 2022-06-03 at 3 16 36 PM" src="https://user-images.githubusercontent.com/1699544/171945565-303c377f-fa95-4e91-ac42-52f08a84e897.png">

This would be a universal change (so, potentially, better error messages across the site, where available).

Writing this to _specifically_ target an invalid branch would necessitate something from the backend telling me that was the issue (rather than just the file not existing).

Thoughts?

**Comment by Enigmatical** [comment]
Circling back around on this because it has been bouncing around "In Progress" for a couple sprints now.

> Can we do an initial check for the schema at the /admin root? (Is this fails, it seems something is misconfigured, and we should link to a FAQ).

This would be an initial check performed by the CLI?  And the FAQ you mentioned doesn't currently exist, correct?  Or did the one that Joel was putting together get released?

> Also, any thoughts on using better branch defaults, so it's less often that users run into this?
```
const branch = process.env.NEXT_PUBLIC_TINA_BRANCH || process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_REF || process.env.BRANCH || "main";
```

I don't have any issues with this, personally.  It is a step up from:

`const branch = "main"`

that I think we use in the starters today.

**Comment by jamespohalloran** [comment]
> This would be an initial check performed by the CLI? And the FAQ you mentioned doesn't currently exist, correct? Or did the one that Joel was putting together get released?

I was thinking a check in the admin frontend. The CLI currently doesn't always run in CI (and when you're working locally, you're usually talking to localhost) so the admin frontend seems like a safe place to surface those issues.

We have this FAQ which we may be able to use:
https://tina.io/docs/tina-cloud/faq/

**Comment by jamespohalloran** [comment]
Here's a little bit more context on this one:
https://www.loom.com/share/f6edb124fcc34038b151b8f4604a6142

I don't want to get too far into solutions mode, but here are a few ideas that could help:
- The /admin originally loads without an error (even when the branch is misconfigured), and that's confusing. It makes me feel like my "collection" is misconfigured because I don't get the error until navigating to a given collection tab. 
- The actual error message still doesn't tell me what's wrong, or guide me how to fix the problem. Can we check for a valid schema at the initial /admin page? (I'd assume we can distinguish this from an actual 404 because we aren't loading an actual document)
- Our "toast" error popup isn't super usable. It's very small, and there's no room for links. If we can't give a specific error in the toast, I'd hope we can at least link to an FAQ.

**Comment by jeffsee55** [comment]
In this scenario we would be getting a 404 on the `.tina/__generated__/schema.json`, that's more clear to us than just any other 404. We can return a specific error message from the server for that. @kldavis4 maybe we already do this?

In addition the dashboard is empty, so we could use that space to do a status check, so rather than dropping the message in the toast we could present it right there in the middle of the page. Thoughts?

**Comment by kldavis4** [comment]
> In this scenario we would be getting a 404 on the `.tina/__generated__/schema.json`, that's more clear to us than just any other 404. We can return a specific error message from the server for that. @kldavis4 maybe we already do this?

The current error message from tina cloud is: `Unable to find '${filepath}' in store for project ${this.appId}: '${this.owner}/${this.repo}', Ref: '${this.ref}'`

**Comment by jamespohalloran** [comment]
Much better experience now that we have better defaults, & compile the client at build time (so error is surfaced earlier)
<img width="998" alt="Screen Shot 2022-08-04 at 2 52 28 PM" src="https://user-images.githubusercontent.com/3323181/182917920-2b4f39f1-0173-4473-909c-89400b84957c.png">
