### ISSUE TITLE
Fields of nested components are not updated immediately

### ISSUE THREAD

**Issue by Perni1984** [tinacms/tinacms#2931]
## Description

When we update fields of nested components, we don't see the updated values in the preview.

More info in the Loom:
https://www.loom.com/share/ea1f956c407f4d479c6f6a70d371edb2

### Steps to reproduce

1. Have a nested component structure
2. Update a field of a nested component (e.g. on the 2nd or 3rd level of nesting)

### Expected result

I would like to immediately see the updates in the preview.

### Actual result

I need to save and reload the page to see the updates.

#### Tinacms Package Versions

```text
├── @tinacms/auth@0.50.2
├── @tinacms/cli@0.60.18
├── next-tinacms-cloudinary@3.5.13
├── tinacms@0.68.6
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser | brave         |
| os      |  ubuntu 20.04       |
| node    |  16.14.2        |
| npm     |     8.5.0    |

**Comment by jamespohalloran** [comment]
I was able to reproduce it by creating a reference to a template, and passing it into a few different fields.
https://www.loom.com/share/1af2d8fcbb8743bda02089248582a945

Here was the workaround for me:
https://github.com/jamespohalloran/nested-blocks-bug/commit/d327dd7923aa7fbf52803aa15c1a8eed0aacffd5

(I created a function to create new templates as needed, instead of passing the template references into the `templates` arry). Want to try that and see if it clears up your issue @Perni1984 ?

**Comment by Perni1984** [comment]
we'll give it a try and report back @jamespohalloran
