### ISSUE TITLE
Fetching a Tina doc that doesnt exist should fail gracefully with no error logs

### ISSUE THREAD

**Issue by llibdude** [tinacms/tinacms#3020]
## Description

When I query for a document that doesn't exist I get the following:
```
Warning: There was an error when fetching data
Error: Unable to fetch, errors:
Unable to find record path/to/doc
```
The response comes back undefined, which is ok, but its the error in the log that gets me.

Locally it's fine, but when hosted on Vercel, sometimes Vercel freaks out I think from the error and actually 500s my page.  

### Expected result

Accessing a page that does not exist should not log an error, the error should be caught gracefully on the filesystem, and a useful response should be returned from the request

**Comment by jamespohalloran** [comment]
For the new client, we have an upcoming update [here](https://github.com/tinacms/tinacms/pull/3031), which throws a more explicit error when the actual data-fetch fails, instead of it quietly blowing up your page downstream. 

How does your data-fetching currently look? I believe the recommended approach would be to catch this error in your getServerSideProps/getStaticProps, and return an errorCode.

**Comment by jamespohalloran** [comment]
I believe this is now complete with the referenced error above. If not, let us know!
