### ISSUE TITLE
Add a "number" field plugin

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#304]
## Summary

`tinacms` should provide a `number` plugin by default. 

The base input would be added to `@tinacms/fields`.

The plugin will be define din `tinacms`

### Basic example

```javascript
{
   name: "temp",
   label: "Temp",
   component: "number",
   description: "The temperature in Celsius",
}

**Comment by dcgoodwin2112** [comment]
I think I have this one working for integer values, but I'm running into an issue where decimal numbers are getting turned into string values on save. Any idea where that might be happening in the codebase? Thanks in advance!

**Comment by ncphillips** [comment]
Ahhh yeah. We've seen a similar issue with Forestry. My hunch: it has something to do with quotes being semi-optional for YAML strings. 

For example, the values `foo: 1` and `foo: "1"` are equivalent. 

I'm assuming the yaml serializer is writing decimals as `foo: "1.2"`. 

Using the text field plugin means `typeof someval === "string"`. 

An actual number field plugin would mean `typeof someval === "number"`, and that would hopefully export correctly.

**Comment by weibenfalk** [comment]
I also checked this out and created a number field with the ability to set steps to increase and decrease. It always write with quotes to the markdown and frontmatter though. Does it matter? =) Haven't found where to change so it writes an integer instead. The thing is that all html inputs return a string and not a number. So even that the input is set to number it returns a string. That input is only for the user so it would not be able to type in anything else than a number but it will always return a string. So guess that's why? Or am I missing something here?

**Comment by jarodpeachey** [comment]
@ncphillips Is this still being worked on by someone, or could I take a crack at this?

**Comment by ncphillips** [comment]
Feel free, I @jarodpeachey I don't think anyone's working on this. Take note of the last thing @weibenfalk mentioned though. There's potentially an issue with the yaml serializion/parsing

**Comment by weibenfalk** [comment]
I created a working version with step value and buttons for step up and down. But as @ncphillips mention the number gets written as a string to the markdown. Couldn't find out why. Don't know if it matters really cause html don't have types ... everything is a string there.

**Comment by jarodpeachey** [comment]
Did you use `<input type="number" />`? Dumb question, but just checking.

**Comment by jarodpeachey** [comment]
I did create a custom number field on a previous Tina project, and I got some errors if I treated it as a number... for example, if I tried to compare it using the `===` operator rather than the `==` operator

**Comment by weibenfalk** [comment]
Yep ... =) The thing is that html don't have types in that sense ... it's still a text input but it is limited to using number when using that type. Don't know if that's the issue here though. I haven't looked at how the inputs gets parsed to the actual markdown file. I tried for several hours to compare types and convert them etc. without luck.

**Comment by jarodpeachey** [comment]
Hmm... have you tried `parseInt()`?

**Comment by weibenfalk** [comment]
Yep .. everything .. still a string in the markdown. But tbh ... don't really know if it matters. It's for showing html in the dom and the number is not going to be used to calculate anything. But that's something that the Tina CMS has to decide if it's important that it is a number type in the markdown. Everything worked fine for me with a string value there also. So the functionality is there ... it's just that it gets the value of a string in the mardown ... aka quotes around itself =) Would love to see your solution if you solve it.

**Comment by PaulBunker** [comment]
Is there a PR open for this? As far as I know values from inputs are always a string. It would be down to whatever is handling the value to change the type. In my opinion this would be beyond the scope of the form field.

**Comment by ncphillips** [comment]
There is not. Feel free to give it a shot @PaulBunker

**Comment by weibenfalk** [comment]
Hey @PaulBunker. Your comment is telling what I've been saying in a better way. =) I have actually created the number field but haven't made a PR. It's fairly straightforward to do. Didn't got to the point yet though to look for where the input value is converted before it is written to the markdown. So it's always a string for me still.

**Comment by ncphillips** [comment]
Do you know if it is a problem with the field, or with the markdown serializer @weibenfalk ?

**Comment by weibenfalk** [comment]
@ncphillips I don't know to be honest. I've got the field to work and as mentioned here it is always a string that is returned from a html input field. I tried to convert it in many ways to a number but it always get written as a string to the markdown. So it should be the serializer, or? Haven't gotten that far and deep in the code base yet to look at the serializer.

**Comment by ncphillips** [comment]
Putting a `parse` function the field plugin might help. For instance, the [TextFieldPlugin](https://github.com/tinacms/tinacms/blob/master/packages/tinacms/src/plugins/fields/TextFieldPlugin.tsx#L37) makes sure an empty value is always an empty string and not `null` or `undefined.

The parse for a number field could be `parse: value => +value`

**Comment by weibenfalk** [comment]
Where do you put this? This is almost exactly what I did .. tried to parse it into a number in several ways .. but always get written as a string to the markdown anyway.

**Comment by ncphillips** [comment]
In the plugin definition for the NumberFieldPlugin.

If it's still happening, I suspect the issue is in the markdown serializer

**Comment by weibenfalk** [comment]
That's where I tried it if I remember correctly. Can try again as soon as I can ... but I guess it's something with the serializer then. What files are for the serializer?

**Comment by ncphillips** [comment]
We use `js-yaml` to serialization. Here's where it's happening for remark.

https://github.com/tinacms/tinacms/blob/master/packages/gatsby-tinacms-remark/src/to-markdown.ts#L25

**Comment by weibenfalk** [comment]
Thanks! Will dive deeper into this!

**Comment by PaulBunker** [comment]
I've also had a look at passing a schema to the serializer as an enhancement for the plugin MDX / Remark ( Unfortunately apple has my laptop for a week now because it stopped charging this morning  :(:(:( its 2 weeks old 😳) 

@weibenfalk Would you please push up a PR with your WIP so I can have a look at it? I did a simple test by adding  [ .add('with Number', () => <TextArea type="number" />)](https://github.com/tinacms/tinacms/blob/adad3e2e562dcdf04b799c13c4290c26b4f5a414/packages/%40tinacms/fields/stories/textarea.stories.tsx#L25) A general approach could work with passing options to the component perhaps? or the simple approach might work as a first step with enhancement further down the road. I'm fresh to both styled components and typescript so my head was a little pickled by the weird javascript.

**Comment by weibenfalk** [comment]
@ncphillips I got it to work now when putting the parse function on the exported object. Where do this function actually run? I can't seem to figure that out. I just put it on the object as a "parse" key and it works now ... but can't find where it is invoked.

**Comment by weibenfalk** [comment]
I've created a PR for this now ... but still don't get it where the parse function actually runs =) Would love to get an explanation of those exported objects from the fields.

**Comment by ncphillips** [comment]
It's executed by [final-form](https://final-form.org/docs/react-final-form/types/FieldProps#parse)

**Comment by weibenfalk** [comment]
ahhhh thank you ... So it is a predefined key from final-form. That's why I couldn't find it in the code. Thanks! It should work now then.
