### ISSUE TITLE
MediaPicker crashes if no 'tina' api is registered

### ISSUE THREAD

**Issue by tabernha** [tinacms/tinacms#3060]
**Summary**

With the update of tina/toolkit to 0.56.35 the media picker crashes if the CMS has no registered api with the key "tina".
I believe the changes that cause this were introduced by adding the media sync button (https://github.com/tinacms/tinacms/commit/9b695c8ce82cae5702bc6c9ccdf8a689c89e4185)

For now, we avoid the media picker crashing by providing a client mock:
`new TinaCMS({..., apis: { tina: { localMode: false, schema: {} } } })`

**Expected Results**

We want to be able to use the media manager and media picker even if we don't use the Tina Cloud Provider (and thus have not registered an API client).

**Comment by jamespohalloran** [comment]
Registering custom content APIs outside of Tina isn't something we're supporting on recent versions of Tina. I'm glad the workaround you noted above works, but there will likely be other breakages in the future around this use case. 
For an idea of the direction we're heading in terms of custom APIs, we're looking into providing a self-hosted version of Tina Cloud, instead of making the front end the point of content-API extension.
