### ISSUE TITLE
Build fails when first running lerna bootstrap without --hoist

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#308]
## Description

When cloning a fresh tinacms repo, running `lerna bootstrap` instead of `npm run bs`, the subsequent `npm run build` will fail with:
```
.../packages/@tinacms/styles/src/Styles.tsx(19,48): semantic error TS7016: Could not find a declaration file for module 'styled-components'. '.../packages/@tinacms/styles/node_modules/styled-components/dist/styled-components.cjs.js' implicitly has an 'any' type.
  Try `npm install @types/styled-components` if it exists or add a new declaration (.d.ts) file containing `declare module 'styled-components';
```

After resolving that issue, there are many other dependencies missing in individual packages.

I am looking to run bootstrap with --hoist so that individual packages can be linked with `npm link` to make testing changes much easier.

### Steps to reproduce

- clone a fresh tinacms repo
- npm install && lerna bootstrap && npm run build

### Expected result

build should run successfully, with all dependencies installed in each package's `node_modules`

### Actual result

Build failed ^

### Environment

Mac OSX 10.14.4

**Comment by jamespohalloran** [comment]
Also, after you resolve the missing package issues one by one, I eventually run into:
```
Could not find a declaration file for module 'styled-components'. .../src/components/modals/ModalProvider.tsx(102,14): semantic error TS2742: The inferred type of 'ModalOverlay' cannot be named without a reference to '@tinacms/styles/node_modules/@types/styled-components'. This is likely not portable. A type annotation is necessary.```
https://github.com/tinacms/tinacms/tree/individual-package-builds

**Comment by ncphillips** [comment]
I removed the bug label because it doesn’t effect the end user. On a side note,  I might make a template for development issues.

 Hoisting is necessary for development because of issues with having multiple versions of packages (I.e. React), so I wouldn’t expect this to work. I’d say don’t run `lerna bootstrap` directly, only run the npm script. That very well could be there problem with that styled-components error. That is, there’s multiple versions of styles components in the dependency tree and tsc is choking on them. 

@dwalkr tried getting hoisting working where only React is hoisted, but ran into similar issues. Maybe he could add some I fo here.

**Comment by ncphillips** [comment]
Closing in favor of #311
