### ISSUE TITLE
blockquote content is treated as inline instead of block

### ISSUE THREAD

**Issue by mAAdhaTTah** [tinacms/tinacms#3118]
## Description

I understand this is somewhat opinionated, but most of the Markdown implementations I've worked with (including GItHub itself) treat the inside of the `blockquote` marks as paragraphs. [This SO answer highlights the difference between `blockquote` & `q`, where `q` means a piece of quoted text inline in a sentence, suggesting paragraphs inside `blockqute`.](https://stackoverflow.com/a/32171048/2757940) The expected/actual below spells this out in more depth. I can provide the parsed output (expected & actual) if that's desired.

I'd be happy to submit a PR for fixing this as well, similar to #3116.

### Steps to reproduce

Create a file with the following MD content:

```md
> Test paragraph
>
> Another test paragraph
```

### Expected result

Blockquote should be parsed like this:

```html
<blockquote>
<p>Test paragraph</p>
<p>Another test paragraph</p>
</blockquote>
```

### Actual result

It's parsed closer to this:

```html
<blockquote>
Test paragraph<br/><br/>
Another test paragraph
</blockquote>
```

#### Tinacms Package Versions

```text
├─┬ @tinacms/cli@0.61.5
│ ├─┬ @tinacms/app@0.0.6
│ │ ├─┬ @tinacms/scripts@0.51.1
│ ├─┬ @tinacms/datalayer@0.2.2
│ ├─┬ @tinacms/graphql@0.63.2
│ │ ├─┬ @tinacms/mdx@0.61.2
│ ├─┬ @tinacms/metrics@0.0.3
│ ├─┬ @tinacms/schema-tools@0.1.0
├─┬ react-tinacms-editor@0.53.26
│ ├─┬ @tinacms/toolkit@0.56.34
│ │ ├── @tinacms/sharedctx@0.1.1
├─┬ tinacms@0.69.1
│ ├─┬ @tinacms/schema-tools@0.1.0
│ ├── @tinacms/sharedctx@0.1.2
│ ├─┬ @tinacms/toolkit@0.57.0
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |         |
| os      |         |
| node    |         |
| npm     |         |

**Comment by jeffsee55** [comment]
Yeah I wouldn't consider this a bug exactly but we're leaning on [Plate](https://plate.udecode.io/) (a plugin system built on top of slate) for a few of our elements and this is one of them. It doesn't support anything other block-like elements inside block quotes (and list items for that matter).

If it's something we want to support we need to make updates in 2 places:

1. Fix it on the `@tinacms/mdx` side, so it doesn't strip out the elements. You can see this logic at work [here](https://github.com/tinacms/tinacms/blob/main/packages/%40tinacms/mdx/src/parse/remarkToPlate.ts#L190-L208)
2. Update the frontend `blockquote` logic, we're getting a lot of this for free from Plate so that'd be the bulk of the work I'd say. Right now we're just [importing it straight into our plugins](https://github.com/tinacms/tinacms/blob/main/packages/%40tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/plate/plugins/core/common.tsx#L52) list. 

This is somewhat in the same boat as list items, and I'd wonder if we add support for nesting block-like elements in blockquotes do we need to do the same for list items, and list items are one thing I'd really rather not handle on our own since they're a fair bit more complex. Still, if it's a popular enough request it'd be worth it.

**Comment by mAAdhaTTah** [comment]
@jeffsee55 Oh, interesting, didn't realize the problem was in the editor. I had been dealing primarily with the `mdx` package that I assumed the issue was how it was parsed there. The first part seems pretty easy, given what I had to do for the previous mdx issues. It's the second part that seems complicated. I can dig into it a bit and see how much work it actually would be. Maybe this is more of an upstream issue in Plate and can be resolved there.

---

Unrelatedly, where is the `react-tinacms-editor` package hosted? There are a lot of references to it in the docs but it seems like with the move to Plate, it's not actually needed for the rich text editor to work. Is that correct?

**Comment by jeffsee55** [comment]
> Maybe this is more of an upstream issue in Plate and can be resolved there.

I believe it's intentional from their perspective to not allow that type of formatting, I personally have seen mixed levels of support for this. In a true rich-text editor most examples I see daily don't support this: Slack, Notion, Discord, other CMSs I've used in the past. And while Github does support it, it's not really a rich-text editor since you write the raw markdown yourself.

Still, since Tina supports markdown as an open format, you might be right about the importance of supporting it.... 🤔 

I'd say let's go for it aside from the list items consideration. For some reason it feels like the behavior across those kinds of blocks should be consistent. The blockquote plugin in Plate is actually [pretty small](https://github.com/udecode/plate/tree/main/packages/nodes/block-quote/src). The list one is a bit of a beast though.

**Comment by jeffsee55** [comment]
> Unrelatedly, where is the `react-tinacms-editor` package hosted

That was previously a part of this repo, but it's no longer maintained. The only reason it's not fully deprecated just yet is because the new rich text editor doesn't support "raw" markdown, so you couldn't use it with a `type: "string"` just yet, though that support will be landing soon. TLDR: yeah you can ignore that package.

**Comment by mAAdhaTTah** [comment]
I can at least say that this came up because I'm migrating from WordPress and that's how their blockquotes are formatted. It makes sense to me semantically from an HTML perspective because if you're quoting from something large enough to be offset by a `<blockquote>`, it's made up of one or more paragraphs; otherwise, you'd use `q` for an inline quote.

I'll dig into it, see how difficult this will be. I will point out that getting this working would mean the rendering itself would change for consumers, which may or may not be desirable.

**Comment by jeffsee55** [comment]
Yeah it's definitely more semantically correct, it was just a matter of what we get for free and don't need to maintain. We've got a fair bit in the pipeline that we're working on so if you're up for taking a stab at it we'd definitely be happy to have this. I wouldn't worry about the list item stuff I mentioned.

> I will point out that getting this working would mean the rendering itself would change for consumers

Since we control rendering for the most part via the `TinaMarkdown` component this isn't too bad. It'll just be a `<blockquote><p></p></blockquote>` so probably not a big deal. 

I haven't thought through any other potential issues bue one other consideration is handling our autoformatting. We allow you to insert a block by typing `> `. When you do that we populate that node with a blockquote (logic is [here](https://github.com/tinacms/tinacms/blob/main/packages/%40tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/plate/plugins/core/autoformat/autoformatBlocks.ts#L75-L80)), but don't worry about that stuff too much, I can jump in on that.

**Comment by mAAdhaTTah** [comment]
I've been digging into this a bit. I asked [and got an answer](https://github.com/udecode/plate/discussions/1826) in the Plate repo, but the recommended method, `wrapNodeChildren, wasn't made available until [16.1.0](https://github.com/udecode/plate/blob/a7bfea5d0f9076ab976c27f295c002e412a05f69/packages/core/CHANGELOG.md#1610), while Tinacms is still on the 14.x series of Plate.

Additionally, my initial experiments also proved a little fruitless. The first few methods I tried didn't seem to accomplish anything, so I'm currently looking at hooking into `apply` & handling all of the relevant operations there, but maybe the reason they didn't work is because we're a bit behind.

Because of these things, I wanted to ask: Is upgrading to the latest version of the editor something you'd consider? If not, I may be able to continue to make progress regardless but `wrapNodeChildren` in particular may need to be brought in for this.

**Comment by jeffsee55** [comment]
@mAAdhaTTah would definitely be open to updating, their major versions are moving quickly but have been easy to update in the past. That being said, `wrapNodeChildren` is pretty lightweight by the looks of it https://github.com/udecode/plate/pull/1768/files#diff-43083e7f398e1cd17beb9f3ddc2eb6ca9e71b7684eb7393c7893afdf1cccb451. I wonder if you can just more or less copy/paste that if we don't get around to update to the latest major version.

**Comment by mAAdhaTTah** [comment]
Yeah, that's definitely to consider, I just wasn't sure if the function it uses were also landed in 14.x or not, in which case, pulling it gets a lot worse. I'm still poking around Plate itself, so not 100% sure yet if the upgrade is needed, but figured I'd ask. If it turns out to be necessary, I'll open a separate PR for the upgrade in isolation.

**Comment by jeffsee55** [comment]
not stale

**Comment by jeffsee55** [comment]
not stale
