### ISSUE TITLE
'@tinacms/next-tinacms-git@0.0.5' is not in the npm registry

### ISSUE THREAD

**Issue by dmouse** [tinacms/tinacms#343]
## Description

Next js related repositories are not registered to install via npm or yarn

### Steps to reproduce

clone this repo, go to `tinacms/packages/demo-next` and run `yarn install`

### Actual result

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@tinacms%2fnext-tinacms-git: Not found".
info If you think this is a bug, please open a bug report with the information provided in "tinacms/packages/demo-next/yarn-error.log".
```

**Comment by ncphillips** [comment]
Hey @dmouse! Thanks for the report 

Running `yarn install` from inside packages is not recommended. Checkout the [README](https://github.com/tinacms/tinacms#development) for how to get started running the demo sites locally.

As an aside `next-tinacms-git` does not meet our standards for general applicability, that's why it's not published to NPM. You can still use it in the demo site though!

I'm going to close this ticket, and I'll update the README to be a bit more explicit.
