### ISSUE TITLE
Many lint warnings

### ISSUE THREAD

**Issue by lyleunderwood** [tinacms/tinacms#370]
176 warnings, 30 potentially auto-fixable.

Is the current eslint config actually what's desired, or are decisions still being made about that? I was thinking about opening PRs to remove lint warning package-by-package.

**Comment by ncphillips** [comment]
The eslint config was added late. We fixed the errors and left warnings due to time constraints. We definitely need to go through and fix them at some point. If you're up for doing that, it would be greatly appreciated! 

But we need to switch `"react-hooks/exhaustive-deps": "warn"` off entirely. It is a bad rule. The assumption that you want to re-run for all deps is just not correct. Doing so breaks tinacms, so until that's turned off please don't run the auto-fixer.
