### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by lyleunderwood** [tinacms/tinacms#373]
Currently when running `npm run test` I think eight out of fourteen packages report zero tests found. Where are the areas of highest potential ROI for increasing test coverage?

**Comment by ncphillips** [comment]
I'll speak to each package. 

`@tinacms/api-git` and `@tinacms/core` are the packages where testing has the highest ROI . It's all plain js, and it's got some complex behaviour and error handling.

I think `@tinacms/form-builder` might benefit from some basic tests to make sure the properties from the plugins and field definitions are used as they should be.

Some parts of `@tinacms/fields` could be tested better. I generally find tests for basic components to be of low ROI. It takes a lot of skill to write tests for them that (a) aren't trivial, (b) test something meaningful, and (c) aren't incredibly fragile.

Similar to `@tinacms/fields`, these packages have low ROI because writing _good_ tests would be incredibly difficult. It would be difficult because they mostly are thin wrappers around `@tinacms/core`, and the bulk of the logic is in hooks.

*  `react-tinacms`
* `gatsby-tinacms-remark`
* `gatsby-tinacms-json`

I'm not so concerned about these packages cause they're mostly styling with little logic:

* `@tinacms/styles`
* `@tinacms/icons`

These packages are really small packages adapters. The first two just connect gatsby to tina, and the third just abstracts HTTP calls. They contain very little logic of their own:

* `gatsby-plugin-tinacms`
* `gatsby-tinacms-git`
* `@tinacms/git-client`

These packages are not published and will probably be removed from the repository:

* `next-tinacms-git`
* `next-tinacms-markdown`

**Comment by lyleunderwood** [comment]
Perfect, tons of useful information here, thank you!

**Comment by ncphillips** [comment]
This is an issues that could never really be "solved". That said, I think the information in it is valuable and that it should be moved to another medium. Perhaps a TESTING.md file in this repository, or maybe a post on community.tinacms.org. 

Do you have any thoughts @lyleunderwood or @dwalkr ?
