### ISSUE TITLE
Ordered list moves each item on line down

### ISSUE THREAD

**Issue by ntorbinskiy** [tinacms/tinacms#3797]
## What do I have?

I have ordered list in my post and all items of this list are on line lower, than number of it

![bug](https://user-images.githubusercontent.com/60061661/230949392-398710c0-bddf-4423-8d3c-20ad1e03e2a0.png)

## Expected behavior 

All items of this list are right after the number of them

![image](https://user-images.githubusercontent.com/60061661/230949758-bf931e51-6f78-40a5-8c4f-d3858f26b30c.png)

### Reproduction

https://github.com/1alexvash/AlexCodeBlog

### Steps to reproduce

1.  Clone git repo by command `git clone`
2. Install all dependencies with command `yarn`
3. Run project with command `yarn dev`
5.  Go for [this](http://localhost:3000/admin#/~/post/2023-01-01-what-is-polymorphism) post (just click this link, and you will open the right post)
6. Scroll to the bottom of the page

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 20.18 GB / 31.88 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Projects\React\AlexCodeBlog\node_modules\.bin\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (112.0.1722.34)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @tinacms/cli: ^1.3.1 => 1.3.1 
    tinacms: ^1.3.0 => 1.3.0
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jeffsee55** [comment]
I think this happens when the `<li>` tag has a `::before` pseudo-class.

The html structure is `<li>::before<div>...`, which we leave unstyled intentionally. This might be something we could style out of the box but it might be easier for you to handle this with a custom `li` component 🤔 . One nice thing about `<TinaMarkdown>` is that it's totally unstyled.

Curious what yours and other's thoughts are there? Should this be left to the end user or should we try to tackle this with inline css?

**Comment by ntorbinskiy** [comment]
Yeas, you are right. created custom `li` component with some styles, which fixed out my problem. Thank you for idea and allotted edtime!
