### ISSUE TITLE
Quick edit does not focus on scalar list items or group fields

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#3967]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

When using { list: true, type: 'string' } in a field it does not seem like the new "quick edit works".

Reproduction: https://github.com/Irsanarisandy/online-profile-nextjs
Video: https://www.loom.com/share/fd14b5b3060d4542822f839ab1876081

Original Found on discord: https://discord.com/channels/835168149439643678/1108946470465449984

CC @jeffsee55 

### Reproduction

 https://www.loom.com/share/fd14b5b3060d4542822f839ab1876081

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.87 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/dev/playground/online-profile-nextjs/node_modules/.bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: 2023.03.13.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 113.1.51.114
    Chrome: 113.0.5672.126
    Firefox: 109.0.1
    Safari: 16.4
  npmPackages:
    @tinacms/auth: ^1.0.3 => 1.0.3 
    @tinacms/cli: ^1.5.14 => 1.5.14 
    tinacms: ^1.5.6 => 1.5.6
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jeffsee55** [comment]
For scalar list items there's a 3rd argument which is the index. 

```
data-tina-field={tinaField(data.about, 'frontend', i)}
```

That will take you to the correct form panel, but won't focus it. I left focus management out of the initial work because it will be a bit of a larger task. Both the group itself (which is the first issue you pointed out) and the individual list item focus are things we need to fix but will require more changes to our fields, and we'll also need to expose the right API for custom fields to also be able to implement this. I'll change the name of this ticket to reflect that.
