### ISSUE TITLE
Styles broken in Demo package

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#405]
## Description

<img width="488" alt="Screen Shot 2019-10-30 at 12 00 48 PM" src="https://user-images.githubusercontent.com/3323181/67869996-fd569500-fb0c-11e9-9ec4-40dd811288b7.png">

There was recently a bug with duplicate `styled-components` imports IIRC. Did `styled-components` become a peer dependency?

### Steps to reproduce

npm run bs
npm run build
cd packages/demo-gatsby
gatsby develop

### Expected result

pretty UI

### Actual result

missing styled

### Environment

MAC OSX Chrome

**Comment by kendallstrautman** [comment]
If i run `npm install && npm run start` in the demo-gatsby it seems to fix the issue

**Comment by kendallstrautman** [comment]
yeah looks like its a peer dep now - https://github.com/tinacms/tinacms/commit/2c852088bf550decf27e9f14aa129e5dee5592d9 - it's odd cause after i run bootstrap `styled-components` is in node_modules...

**Comment by ncphillips** [comment]
Yeah this is a weird one. I suspect there's somehow multiple versions of `styled-components` getting installed because of the `peerDependency` shift.

The reason I think this, is because it is only styles from `@tinacms/styles` that aren't working. I think the styles defined directly in `tinacms` are good. (That needs to be confirmed)

**Comment by ncphillips** [comment]
For reference #362
