### ISSUE TITLE
Eleventy integration guide?

### ISSUE THREAD

**Issue by trst** [tinacms/tinacms#406]
Howdy!

TinaCMS looks super rad and it looks like it would scratch a current itch as a git-backed CMS for various Eleventy (11ty) projects I have been working on. While I haven't looked into it deeply enough at this point, is this integration possible?

Also, I would be willing to help document that process with a tiny helping hand from the community where needed.

Thanks again for your hard work!

**Comment by trst** [comment]
Doh! Of course it does! It says react-based right on the tin.

I have used alternatives in the past, but while they're awesome, they just weren't suitable for the arrangement that my team and I had envisioned, namely not requiring external accounts/management for small internal projects.

I suppose it'd make more sense to close this task and open a new ticket with a more generalized direction, e.g., Add Support for Non-React Based Applications, or whatever :stuck_out_tongue:

**Comment by jpatters** [comment]
I have some ideas on how we can make it work with other static site generators. So that ticket would be most welcomed.

**Comment by ncphillips** [comment]
> Tina relies on React High Order Components

> It says react-based right on the tin.

We're going to have to update our docs a bit. Neither of these statements are correct. 

TinaCMS is _not_ React based, we just focused on React integration first. Sure, the sidebar is React, but the core of the CMS doesn't know anything about React. As far as the core of Tina is concerned the sidebar is just another consumer, like the rest of your site.

`react-tinacms` is just provides some helpers for accessing the CMS and using it in React components, _but React is by no means required to interact with the CMS on your site_. 

`gatsby-tinacms-remark` provides the `remarkForm` higher order components because Gatsby is React based and that's the API that makes senses.

The way Tina is built, it's already totally possible to add other adapter libraries (e.g. `vue-tinacms`) for interacting with the cms .

**Comment by trst** [comment]
Thank you for the clarification @ncphillips . I'll take a look at the implementations and report back with progress/issues.

**Comment by surjithctly** [comment]
@ncphillips I see you closed two issues related to this. 

Do you mean TinaCMS currently supports Eleventy?

**Comment by DirtyF** [comment]
It means we only support React integration for now, if you can use React with Eleventy, then you might be able to use Tina, but if you are to add React to Eleventy, you might as well use a React framework like NextJS then.

**Comment by matbrgz** [comment]
> It means we only support React integration for now, if you can use React with Eleventy, then you might be able to use Tina, but if you are to add React to Eleventy, you might as well use a React framework like NextJS then.

This is exactly what I'm doing. I'm using NextJS with Eleventy, but now I'm considering use Tina. Any idea how to start?
