### ISSUE TITLE
Integration with non-react based applications

### ISSUE THREAD

**Issue by trst** [tinacms/tinacms#407]
## Summary

Provide the ability to adapt TinaCMS so it will integrate into other applications without the requirement that they also be react-based applications.

### Motivation

Many static site generators (SSG), like Jekyll or Eleventy, use a flat, typically markdown-based, file management and are compiled into static HTML and most SSGs do not have a React requirement. It would be useful to the community to access TinaCMS's editor and write directly into a git repo but either: a) not have to require React, or b) provide some plugin, adapter or bridge to provide access to framework agnostic applications.

The expected output would probably be, in simplest terms, the ability to add TinaCMS as a dependency and on `SSG-OF-CHOICE server` (or whatever the exact command would be) provide access to TinaCMS in the live preview of the site. Editing would happen in TinaCMS and all file changes would be committed to the underlying repository.

Presumably this would also deal with other issues like #331 where workarounds for alternative frameworks, like Svelte/Sapper, Vue/Nuxt, Gridsome, etc., would not need to be built separately.

**Comment by ncphillips** [comment]
I'm going to close this issue because Tina has already been designed with this in mind, and the scope of this ticket is too broad. 

The core of Tina is _not_ react specific, and neither are packages for interacting with git. I wrote a bit more about that [here](https://github.com/tinacms/tinacms/issues/406#issuecomment-548192924).

In short, packages like `react-tinacms` and `gatsby-tinacms-git` are just thin wrappers around the core of the cms. 

Exactly how each of these framework adapters are built will be specific to each stack. Because of that, I'm closing that in favor of opening specific issues (e.g. #331 )

**Comment by heyakyra** [comment]
Added one for `elm-pages` as well: #515
