### ISSUE TITLE
Unable to edit a template with list: true inside of rich text

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#4074]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

When using a template with list: true inside of a rich text we are unable to edit it

### Reproduction

https://www.loom.com/share/84b8826968a44f49becdc834dc5e8d64

### Steps to reproduce

1. Add the a template that looks like the following to any rich text section.
```ts
          {
                name: "imagesSection",
                label: "ImagesSection",
                fields: [
                  {
                    name: "images",
                    label: "Images",
                    type: "object",
                    list: true,
                    fields: [
                      {
                        type: "string",
                        label: "Image",
                        name: "image",
                      },
                    ],
                  },
                ],
              },
```

2. Try and edit the imagesSection and see that you get stuck in a loop

### System Info

```shell
tina-cloud-starter with latest TinaCMS versions
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jeliroco** [comment]
Can confirm I am encountering this issue as well. While templates with "list: true" are editable outside of a rich-text element, the exact same template embedded in a rich-text will fail to open the CMS menu. Instead the sidebar will go blank, or it will kick the user back to the "Documents" list.

**Comment by HenrySkup** [comment]
Same issue here...

**Comment by coreyaus** [comment]
Hey team,

I've just opened a PR to resolve this issue [here](https://github.com/tinacms/tinacms/pull/4409). For background, we ran into the same bug recently and found the following:

- Currently this bug only occurs for rich-text templates with `inline: true`
    - I think it was resolved for non-inline rich-text templates by this earlier PR (merged on 15 July 2023): https://github.com/tinacms/tinacms/pull/4044
- The bug is present for rich-text templates if they either
    - contain a list field (like in Logan's screenshot above)
    - OR if they contain an object field

The full details and an updated screen recording are visible in [Fix inline rich-text templates with nested object or list fields #4409](https://github.com/tinacms/tinacms/pull/4409)

Cheers, and have an excellent end to the year!
