### ISSUE TITLE
Inline-Editing: Markdown Toolbar should be sticky on longer content

### ISSUE THREAD

**Issue by kendallstrautman** [tinacms/tinacms#425]
## Summary

Currently when you are editing longer posts using the liveRemarkForm, the toolbar stays at the very top of the content. Ideally while you are composing content you will always have easy access to this toolbar. 

### Basic example

More thought might need to be had on the UX of this feature, but as a bare minimum we could make the toolbar sticky to the top as the user scrolls down. 

### Motivation

Expected outcome would be that the while in inline-editing mode, the markdown toolbar will always be easily accessible.

**Comment by scottgallant** [comment]
Good issue. With tools like MS Word or Google docs, the toolbar is fixed and the document scrolls. With Tina's in-line mode, the entire page scrolls and when you write long articles you find yourself scrolling to the top to access the toolbar. This is likely why Dropbox paper and Medium.com use the "highlight" toolbar option. 

<img width="825" alt="Screen Shot 2019-11-11 at 7 28 49 PM" src="https://user-images.githubusercontent.com/776019/68639481-8ed4e800-04b9-11ea-895e-ded97a4781de.png">

**Comment by spbyrne** [comment]
The inline editor certainly needs improvement, but it may be hard to make a sticky toolbar given the user may have a site with a fixed header (or something else) that could get in the way. There wouldn't be any reasonable defaults.

Here's a number of ways we can improve the situation:

1. Add a static class name so devs can easily work with the toolbar in their stylesheet so that `position: sticky` could be implemented in a way that works with their situation.
2. We could offer an option to fix the toolbar to a particular spot, like next to the Tina toggle. This wouldn't depend on CSS from their site to work, so would be a more universal option.
4. We could offer a mode that displays the toolbar next to the current selection (inside liveRemarkForm). For this to work well we'd also need to provide control over what's displayed in the toolbar so the developer can opt for a stripped-back version.

**Comment by scottgallant** [comment]
@spbyrne why not the Dropbox-paper-style solution?

**Comment by spbyrne** [comment]
I suppose that's more of a hybrid between 2 & 3; a toolbar that's always displayed but moves to the cursor when text is selected. That could be a good solution since it wouldn't affect discoverability.

It's annoying if it's a large toolbar that keeps jumping around on your screen as you select text, but we could do some testing to see what looks good. I suspect having an always fixed toolbar *plus* a toolbar that pops up when text is selected would be the best of both worlds.

**Comment by jonmiller0** [comment]
Maybe an expanding rich text editor from the sidebar (quick concept attached)? I think this works well with the existing UI and will help users know that all editing happens on the left-hand side whether its inline editing or not. I also attached a sticky top nav option that gives more horizontal room for further editor expansion (showcased with the heading, font, and font size additions). 

![rich-text-idea-1](https://user-images.githubusercontent.com/22771842/69920163-2dfe5700-144a-11ea-81e0-c9124e558c49.png)
![rich-text-idea-2](https://user-images.githubusercontent.com/22771842/69920164-2e96ed80-144a-11ea-901f-b7e33abc2870.png)

**Comment by spbyrne** [comment]
Thanks @jonmiller0 I think that's a really solid concept. I like that since it's a pane it can expand based on what controls are available. The main thing I'd like to avoid is a major splintering of UI and this could help solve that.

I know a concentrated effort is needed on the inline UI, so I'll be working on this very soon.

**Comment by jonmiller0** [comment]
Thanks, @spbyrne. Happy to help assist in implementing these updates. I can continue to flesh out this design further since my quick concept didn't showcase the nested options within the inline UI.

**Comment by scottgallant** [comment]
Great stuff @jonmiller0. Personally, I'm a fan of the 2nd option (fixed to the top) since we plan on decouple the in-page mode from the sidebar stuff in the future.  @jimafisk put it well in this tweet last week:  https://twitter.com/jimafisk/status/1199694259269582849

We're planning on investing some time into designing and prototype a few different options for the in-page toolbar in the coming weeks. Do you want to be part of that?

**Comment by ncphillips** [comment]
@all-contributors please add @jonmiller0 for ideas

**Comment by jonmiller0** [comment]
Thanks, @scottgallant. Yes, I would love to be a part of that!

**Comment by scottgallant** [comment]
I put together these notes after our call yesterday after we discussed some long-term ideas of how the editing experience should work. It's clear that we need to tightly integrate the in-page editing experience and the UI editing experience (sidebar). 

This is what we need to consider: 

1. A global save/publish/delete button. In the future, we might add more to this like _draft-status_ or _revision history_.
2. When editing text in-page, show a fixed, rich-text toolbar 
	1. Ability to insert components into text from the toolbar (i.e. a call-to-action button) 
3. Ability to insert “page blocks" 
4. How do we indicate that a page-block is editable? How do you activate edit mode? 
5. When editing a page block, show an overlayed UI (sidebar, modal?) with only fields for that block
6. How do you access "global" or "meta" things like navigation menus, SEO settings, or theme options? 
7. How do you reorder a page block? 

@spbyrne I'm not convinced that 1 and 2 should be the same UI, but I'm not opposed to that. 

Looking forward to seeing what we come up with.

**Comment by weibenfalk** [comment]
Hey ... Thought it would be fun to check out the code in Tina. So this was a great "beginner challenge" to solve to get to know the code a little bit. You're setting the position to sticky on this one but it won't work as the menu need to go in a container with all the content for that to work.

It was a bit tricky but I've come up with a solution where I use scroll event, a useEffect and a couple of states. Then change the css in the styled component depending on these values.

Is this something you want a PR on? I haven't added anything to the menu ... just made it sticky. 

You can see how it works here:

https://www.dropbox.com/s/4cnln5coc8s493s/tina-inline-editing-sticky.mp4?dl=0

**Comment by spbyrne** [comment]
This is awesome, @weibenfalk. I'm working on styling the 'Add Heading', 'Add Image' and other blocks related UI right now, this would be a great addition to that as I haven't tackled the menu yet.  A PR would be fantastic! 😄

**Comment by weibenfalk** [comment]
Great! I've created a PR now, branch  weiben#425  ... check it out and see if you can use it. I think that this "much" code is needed as the structure is now. There's no way to just set the position to sticky right now and get it to work. =)

**Comment by spbyrne** [comment]
Thanks! I'll take a look this afternoon. At first glance it looks great, though.

**Comment by weibenfalk** [comment]
Sounds great @spbyrne =)

**Comment by kendallstrautman** [comment]
Closing as this was implemented via #528, although there's still a bug, see #618 with a PR to fix #661
