### ISSUE TITLE
Remove the 'stale' bot

### ISSUE THREAD

**Issue by gloopsies** [tinacms/tinacms#4282]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

The 'stale' bot closes valid issues because nobody had time to look at them for a short while. They are not solved and should still be looked at, but bot closing them just means nobody will ever look at those issues even if they are completely valid and should be looked at.

eg. #3811 

### Reproduction

N/A

### System Info

```shell
N/A
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jamespohalloran** [comment]
I do personally find use out of it, mainly because it flags issues that have been sitting around for a while that either:
a) Should be given another look
b) May have already been fixed
c) May no longer be relevant

I think we should at minimum look at tweaking the timers though. Tickets definitely become stale too quickly, and maybe shouldn't get auto-closed (or at least not as soon as they do.)

**Comment by jamespohalloran** [comment]
Just opened a PR here that increases the stalebot timer, and the timer to auto-close issues:
https://github.com/tinacms/tinacms/pull/4379
