### ISSUE TITLE
Escaping does not work properly in mdx editor

### ISSUE THREAD

**Issue by KVPlotnikov** [tinacms/tinacms#4503]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I am experiencing an issue with the MDX editor in TinaCMS where curly braces are not being escaped properly. When I input a string like `GET/{uuid}` into a rich-text field formatted in MDX, the editor initially adds an escape character (`\`) before the curly brace (`{`). However, after saving and reloading the document, the escape character disappears, and the editor throws an error saying "Unexpected expression uuid".
![2024-04-23_17-15-45](https://github.com/tinacms/tinacms/assets/103137008/49d75c22-0f8b-473c-bd6c-aecabb1997e7)
![2024-04-23_17-16-06](https://github.com/tinacms/tinacms/assets/103137008/cfd4dff5-7fff-4267-88ad-6a3c1507239a)
![2024-04-23_17-16-22](https://github.com/tinacms/tinacms/assets/103137008/f15630da-575c-4fad-b857-2a1aad293b9a)
![2024-04-23_17-16-48](https://github.com/tinacms/tinacms/assets/103137008/bf529fd4-6434-409a-9e1b-8bf7ecd29389)

### Reproduction

https://github.com/KVPlotnikov/tina-self-hosted-demo

### Steps to reproduce

1. Open the MDX editor in TinaCMS.
2. Enter the string `GET/{uuid}` in a rich-text field.
3. Switch the view from rich-text editor to MDX format view; observe that the editor automatically adds a `\` before the `{`.
4. Save the document and reload the page OR just switch to rich-text editor mode and then row-editor again.
5. The previously added escape character is gone, and an error appears concerning the `uuid` expression.

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 10.45 GB / 31.85 GB
  Binaries:
    Node: 20.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - D:\projects\astral\landing\node_modules\.bin\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 123.0.6312.123
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @tinacms/auth: ^1.0.4 => 1.0.4
    @tinacms/cli: ^1.5.43 => 1.5.43
    @tinacms/datalayer: ^1.2.33 => 1.2.33
    tinacms: ^1.6.1 => 1.6.1
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kulesy** [comment]
## Reopening this issue

This issue was auto-closed by the stale bot, but it's still a valid bug that needs to be addressed. Recent discussion in #6651 has highlighted that this is a blocking issue for users working with static site generators.

## Additional Context

**Reproduction repository:** https://github.com/nkuehn/reproduce-tina-incompatible-mdx

**Related to MDX expression handling:** This issue is part of a broader problem with MDX expression support. MDX comments (`{/* ... */}`) have the same root cause - they're treated as expressions and cause errors.

**Connected to v4.1 work:** This relates to issue #6323 which is already planned for v4.1 and addresses MDX parsing edge cases.

## Root Cause

The issue occurs in `packages/@tinacms/mdx/src/parse/remarkToPlate.ts:114-123` where MDX expressions are explicitly rejected:

```typescript
case 'mdxFlowExpression':
case 'mdxjsEsm':
  throw new RichTextParseError(
    `Unexpected expression ${content.value}.`,
    content.position
  );
```

This means **any** curly brace content (whether escaped or not) is treated as an MDX expression and throws an error.

## Impact

This is a **breaking issue** for:
- API documentation (REST endpoints like `GET/{uuid}`)
- MDX comments in content
- Any content with literal curly braces

Let's address this as part of the v4.1 MDX improvements (#6323).

**Comment by saltboxsolutions** [comment]
Still present on **tinacms 3.12.1** (`@tinacms/mdx` 2.2.1, `@tinacms/graphql` 2.4.10), and it bites on *import* as well as on save — so a document can arrive in a state where it cannot be opened at all.

Migrating 55 posts out of Contentful, two of them contained Google Ads ValueTrack placeholders in ordinary prose (`{lpurl}`, `{campaignid}`). Written as MDX escapes:

```mdx
The first variable, \{lpurl\}, is replaced automatically.
```

`astro build` renders that as literal text, per the MDX spec. Tina fails to index it:

```
Error parsing file tracking-templates.mdx from collection blog.
  OriginalError: Unexpected expression lpurl. at line 45, column 43
```

A second file, whose prose contained a pasted KaTeX fragment (`\\text\{New CTR\}`), failed differently:

```
Could not parse expression with acorn: Unexpected content after expression
```

### The diagnosability half

That is the part that cost the most time, and it may be worth splitting out: `tinacms audit` reports **only the file name**. The messages above are not printed anywhere — we got them by instrumenting `TinaParseDocumentError` in `@tinacms/graphql` by hand. From a content author's seat the failure is "this document is broken", with no line, no column, and no indication that a brace is special.

Two things would have made this a five-minute fix instead of an afternoon:

1. Escaped braces treated as literal text, as MDX itself does (the actual bug), and
2. failing that, `audit` printing the original error — file, line, column, offending characters — without needing a patched dependency.

### Workaround

Our importer rewrites brace placeholders as inline code (`` `{lpurl}` ``) and normalizes pasted KaTeX before writing the MDX. That is fine for a migration; it is not something an author typing into the rich-text editor can be expected to know.

Environment: tinacms 3.12.1 · @tinacms/cli 2.6.1 · @tinacms/mdx 2.2.1 · self-hosted/local mode (`tinacms dev`) · Astro 5.18.2 · Node 24.13.0 · macOS 15.

(Also related: #5761 and #5829 for the double-brace variant.)
