### ISSUE TITLE
Editorial Workflow - Pull requests are not created

### ISSUE THREAD

**Issue by amankumarrr** [tinacms/tinacms#4514]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

@samsmithssw @sethdaily @scottgallant 

It seems like since enabling the Editorial Workflow feature, we're encountering an intermittent issue where Pull Requests are not being created when branches are created. When examining the changed files, it appears that nothing has been modified. Since this issue is hard to reproduce consistently, it's challenging to identify the root cause.

### Reproduction

N/A

### Steps to reproduce

N/A

### System Info

```shell
N/A
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by samsmithssw** [comment]
@amankumarrr @sethdaily @scottgallant
This is the branch that we discovered this bug on: https://github.com/SSWConsulting/SSW.Website/tree/tina/samsmith

I made changes to a web page in TinaCMS, and then when I went to raise the PR I found that it hadn't saved the changes. So I lost all of my work :(

**Comment by sethdaily** [comment]
⚠️ Important - this bug is making edits not save properly
@scottgallant @adamcogan consider prioritizing this

@camillars and I have both experienced the same thing (apologies for not having recorded a video of the problem)

- we make edits
- we save and create a branch
- we go to github and the new branch is created, but no record of any changes
