### ISSUE TITLE
Content Save Failure When Re-Using Deleted Branch Name

### ISSUE THREAD

**Issue by samsmithssw** [tinacms/tinacms#4516]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

@amankumarrr
I made some content changes to a webpage and then when I saved the changes and created a new branch this error came up. All of my changes were lost.

<img width="1439" alt="Screenshot 2024-05-02 at 11 03 46" src="https://github.com/tinacms/tinacms/assets/115435510/0b8d2095-6e7b-41ea-b257-de5edc8407cd">
Figure: First error message
<img width="1439" alt="Screenshot 2024-05-02 at 11 06 05" src="https://github.com/tinacms/tinacms/assets/115435510/c7f08895-80ed-4a14-af6c-ed48b093aea3">
Figure: Second error message once first was closed

### Reproduction

n/a

### Steps to reproduce

1. Make changes
2. Save changes
3. Create a branch
4. Get it merged.
5. Make changes again
6. Save changes again
7. Create a branch with the same branch name.

### System Info

```shell
n/a
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kldavis4** [comment]
@samsmithssw what error(s) are there in the browser console?

**Comment by samsmithssw** [comment]
> @samsmithssw what error(s) are there in the browser console?

This is the error message in the console

<img width="1439" alt="Screenshot 2024-05-03 at 14 53 54" src="https://github.com/tinacms/tinacms/assets/115435510/0f6f5d4c-c84c-477e-afee-ec12e5e08efc">
**Figure: console error message**

**Comment by kldavis4** [comment]
thanks - so you are re-using the same branch name? Does it happen when you use a different branch name in step 7?

**Comment by amankumarrr** [comment]
@samsmithssw 

Hey @kldavis4,

The issue arises when an old branch is deleted on GitHub, and an attempt is made to create a new branch with the same name in Tina. The editorial workflow permits the creation of such a branch since it's deleted on GitHub. However, upon indexing in the Tina Cloud, a conflict arises as the branch already exists there.

**Potential solutions:**

1. Implement a check before indexing in the Tina Cloud to prevent the creation of a branch with the same name.
1. Allow users to delete branches directly from the Tina Cloud.

**Comment by amankumarrr** [comment]
@kldavis4 is it something we need to fix it on our end?

**Comment by kldavis4** [comment]
Unclear at this point. Just needs to be investigated because under normal circumstances there shouldn't be a branch naming conflict
