### ISSUE TITLE
On Deploy: window is undefined from react-tinacms

### ISSUE THREAD

**Issue by kendallstrautman** [tinacms/tinacms#462]
## Description

I'm getting this error that's failing the build of my gatsby starter. Looks like its coming from `use-cms` in `react-tinacms`. I'm confused because it seems like since I set the NODE_ENV to production, `use-form` should return early and never call `use_cms()`, but obviously its still being called. Seems like its running during SSR?

 __To be clear__ this error isn't referencing the global window obj, its coming from within Tina. Also worth noting this error popped up after upgrading. 
``` javascript
failed Building static HTML for pages - 4.683s
3:01:29 PM:   WebpackError: ReferenceError: window is not defined
3:01:29 PM:   
3:01:29 PM:   - index.js:1 f
3:01:29 PM:     node_modules/react-tinacms/build/index.js:1:327
3:01:29 PM:   
3:01:29 PM:   - index.js:1 r
3:01:29 PM:     node_modules/react-tinacms/build/index.js:1:890
3:01:29 PM:   
3:01:29 PM:   - index.js:1 
3:01:29 PM:     node_modules/react-tinacms/build/index.js:1:1324
```

### Steps to reproduce

Checkout https://github.com/kendallstrautman/brevifolia-gatsby-tinacms, clone and deploy to Netlify. 

### Expected result

The site should build.

### Actual result

The error above occurs. 

### Environment

| react-tinacms   | 0.8.0     |
| ------- | ----------- |
| yarn     | 1.19.0    |
| node    | 12.6.0    |

**Comment by Foxhunt** [comment]
I get the same error when trying to setup the NextJS example.

https://github.com/Foxhunt/tina-test

I assume the problem problem is caused by tinacms@0.6.0 depending on react-tinacms@0.6.0 not react-tinacms@0.6.1-canary.1793.

**Comment by kendallstrautman** [comment]
Yeah its interesting, I have a next.js site working (without this error) with tina running on tinacms@0.6.0...https://github.com/kendallstrautman/brevifolia-next-tinacms - So I figured it was a problem with releases later than that, but I guess not.

**Comment by ncphillips** [comment]
The problem is that `tinacms` is depending on a different version of `react-tinacms`. This means there are actually two versions of `react-tinacms` being used. 

Why is this a problem? **Because global variables are the devil and React Context objects are global variables.**

Each installation of `react-tinacms` has it's own instance of:

```typescript
export const CMSContext = React.createContext<CMS | null>(null)
```

* `gatsby-plugin-tinacms` is referencing the instance in `react-tinacms@0.8.0`
* `tinacms` is referencing the instance in `react-tinacms@0.5.0`

The `CMSContext` from `gatsby-plugin-tinacms` is the one that wraps the app and the one used in `tinacms` is not. This should break _both_ browser and ssr builds, but the `react-tinacms` has that handy `|| window.tinacms` that makes it work in the browser. If I remove that line (as I should) it will break for both (as it should).

So I'll fix the dependency issue, remove that line, and hot-fix this to `latest`.

**Comment by ncphillips** [comment]
I pushed out the change and it seems to have resolved this issue.

Could @kendallstrautman and @Foxhunt confirm?

**Comment by Foxhunt** [comment]
@ncphillips can confirm.

Issue is resolved.
