### ISSUE TITLE
 👀 Spike - 🔌 Rich text - add mermaid plugin

### ISSUE THREAD

**Issue by wicksipedia** [tinacms/tinacms#4679]
Great docs sites have diagrams

It would be awesome if we were able to add mermaid diagrams to sites built with Tina!

https://mermaid.js.org

We could leverage exising implementations - https://github.com/remcohaszing/rehype-mermaid

Ideal support would include:

- Flowchart
- Sequence Diagram
- Class Diagram
- State Diagram
- Entity Relationship Diagram
- Pie Chart
- Quadrant Chart
- Requirement Diagram
- Gitgraph (Git) Diagram
- C4 Diagram
- Mindmaps
- Timeline
- Block Diagram

**Comment by JackDevAU** [comment]
Update:

So there are 2 parts to implementing this. First is implementing it with Platejs then actually saving and parsing the markdown. 

**Plate Integration:**  This step involves integrating Mermaid diagrams within the Plate editor. I've partially completed this by using `mermaid` to render within the editor using a custom component/plugin. This has some bugs at the moment but I believe these can be sorted out. **Effort 8** 

**Parsing and Saving Diagrams:** The next challenge is parsing and saving these diagrams. Since TinaCMS uses `remark` under the hood for saving and loading, we'll need to implement a custom solutions to ensure that Mermaid syntax is correctly parsed, saved, and rendered correctly. This part is still under exploration, as this is the core of Tina and is quite complex... to handle the full range of Mermaid diagrams seamlessly within the content model this will be some work. I'm unsure if using https://github.com/remcohaszing/rehype-mermaid will fix the issue but we can potentially add rehype. **Effort 16**
