### ISSUE TITLE
🐛  Bare Bones Starter – A lot of data in the "Hello World" Post page is shown

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tinacms#4692]
Please see the below screenshot of 'Posts | Hello World'.

Is this intended behavior?

![Image](https://github.com/user-attachments/assets/783d5aff-d68a-4191-a007-862e3f91531c)
**Figure – display**

### Reproduction

npx create-tina-app@latest | npm | bare bones starter

### Steps to reproduce

Create a bare bones starter and go to http://localhost:3000/posts/HelloWorld (or other port being used).

### System Info

System:
    OS: macOS 13.6.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 541.51 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
    Yarn: 1.22.22 - ~/posts-error-repo/node_modules/.bin/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
  Browsers:
    Chrome: 127.0.6533.74
    Safari: 16.6
  npmPackages:
    @tinacms/cli: ^1.5.46 => 1.5.46 
    tinacms: ^1.6.4 => 1.6.4 

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by wicksipedia** [comment]
This is intentional, the bare bones starter is "stripped down to just the essentials" - it does as little as possible with the data.

There are other templates that make the posts look nicer by adding in things like Tailwind and apply styles.

This template doesn't try to add in things like CSS frameworks so that you don't have to rip them out if it isn't the one you like to use.
