### ISSUE TITLE
`gatsby-tinacms-json` requires JSON nodes to have `Json` in their type

### ISSUE THREAD

**Issue by dwalkr** [tinacms/tinacms#471]
# Description

`gatsby-tinacms-json` adds additional metadata to JSON nodes created by `gatsby-transformer-json` by checking if the node's type contains the text "Json". However, `gatsby-transformer-json` exposes an option to customize the name of the graphql type generated by the plugin. If a consumer uses a custom type that does not include "Json", `gatsby-tinacms-json` does not attach the necessary metadata.

### Steps to reproduce

https://github.com/BoyWithSilverWings/gatsby-wedding-theme/blob/feature/setup-tina/gatsby-theme-wedding/gatsby-config.js#L23

### Expected result

The JSON nodes can be used with Tina.

### Actual result

An error is thrown because `rawJson` and `fileRelativePath` fields do not exist on the node.

**Comment by NurbekGithub** [comment]
I am not sure if it's related, but I am experiencing problem when trying to save my changes. When I clock save button I see "commit" POST request was sent and returned 412 error(Precondition Failed). I assume that this is because files array is [null]
![image](https://user-images.githubusercontent.com/24915724/68944923-4e3ade80-07d9-11ea-9fe9-1dfa7ed757be.png)
 A little investigation shows that. this is because onSubmit function expects data: {fileRelativePath: ""}, but actual structure is data: {jsonNode: {fileRelativePath: ""}}. Hope it helps
