### ISSUE TITLE
How can editors use Tina in Production?

### ISSUE THREAD

**Issue by sorleone** [tinacms/tinacms#474]
While reading here:

https://tinacms.org/docs/concepts/sidebar#hiding-sidebar-in-production

I have learned that Tina hides the sidebar in production. So how are the editors of the website supposed to edit it then? Doesn't this defy the whole purpose of CMSs if we are only able to edit the website in development? How can can I have a login page under the `/admin` route like most CMSs have, that allows the editors to login and get redirected to a version of the website that shows the sidebar? Can we use something like Netlify's [Git Gateway](https://github.com/netlify/git-gateway) to achieve this so that there wouldn't be the need of some user DB nor for them to sign-up on GitHub?

**Comment by scottgallant** [comment]
Tina [Teams](https://tinacms.org/teams) solves this problem (coming soon).  This allows you to run Tina in the cloud so your non-developers friends can edit.   When people edit content using Teams, it commits to your repo (like Netlify CMS or Forestry.io).

**Comment by lumberman** [comment]
I think it should be stated more clear on Tina website. Just wasted an hour playing this with CMS not realizing it won't work for my client due to this limitation.

**Comment by scottgallant** [comment]
@lumberman sorry to hear that. If you reach out to me in the [slack community](https://tinacms.slack.com/join/shared_invite/enQtNzgxNDY1OTA3ODI3LTNkNWEwYjQyYTA2ZDZjZGQ2YmI5Y2ZlOWVmMjlkYmYxMzVmNjM0YTk2MWM2MTIzMmMxMDg3NWIxN2EzOWQ0NDM), I'll make sure you have early access to the hosted version of Tina (https://tinacms.org/teams). 

My slack user name is `@scott gallant`.  I suspect it will be ready in a week or so, but let's discuss in slack.

**Comment by BjoernRave** [comment]
@lumberman there is also this post in the tinacms forum: https://community.tinacms.org/t/next-js-needing-tina-in-production/29

haven't tested it though, so not sure it works

**Comment by BjoernRave** [comment]
I would also still prefer to have a option to enable tina in production, so I can show it for the admin user. Also a way to send the texts to a graphql backend would be so great

**Comment by ncphillips** [comment]
@BjoernRave we've actually changed this behaviour. It hasn't been released yet though. It will be by next Monday:

See #520 for details

**Comment by jamespohalloran** [comment]
We just published a blog post describing [how editing in the cloud will work for teams](https://tinacms.org/blog/editing-on-the-cloud/).

**Comment by seansean11** [comment]
@jamespohalloran the blog post is great and I appreciate that the teams effort to inform people on how to use TinaCMS.  I still think there is a big gap for people getting familiar with the project in the main docs.  Especially in how the editing environment is intended to be used.  I was under the impression for a few weeks while working on a TinaCMS project that I would simply be able to deploy my project to production and would have some sort of GitHub auth'ed editor available on the same instance.  

As a quick note for others that also are trying to grasp this - you need to deploy 2 instances of your app.  Using the `gatsby-plugin-tinacms` configuration you can toggle the editor based on environment.  You **cannot** have access to your TinaCMS editor if you compile down your entire application for production.  You will need to setup your repo to build and deploy one instance to production and you will need to run another instance of your code running it with something like webpack-dev-server (in the case of Gatsby).  You will probably need to create your own authentication so that only your editor admin's can access this instance of the app.  It will need to be set up with the correct gatsby-tinacms-git options (`sshKey` and `gitRemote`) in order for it to push the editors changes to your git repo.

I would imagine all of this is necessary until `TinaCMS Teams` or competing services are available.

**Comment by DirtyF** [comment]
The core team just released some guides on how to run Tina with Next.JS and GitHub: https://tinacms.org/guides/, it's exactly how https://tinacms.org runs in production. 
The team is still working on the architecture of a Tina-powered service for teams, but there's still weeks and weeks of work left.

**Comment by DirtyF** [comment]
Closing this issue, as it's something that can be discussed on the [community forum](https://community.tinacms.org/).

**Comment by shivammodi456** [comment]
Is there any way is available that Tina Cms can be used in **Production**? Anyone can share doc regarding it
