### ISSUE TITLE
Feature Request: Support editing MDX files in Gatsby sites

### ISSUE THREAD

**Issue by c-kirkeby** [tinacms/tinacms#550]
## Summary
Currently it doesn't appear possible to simply use MDX interchangeably instead of MD, which means that one would have to pick between the power of MDX and the utility of TinaCMS, or attempt to embed MDX components (which I can't find any docs on, but seems to be mentioned in a [dev.to article](https://dev.to/tinacms/announcing-tinacms-ddk)).

### Basic example

Ideally the new API would be pretty similar to the existing remark API, but allowing the full power of MDX in the sidebar editor: https://www.gatsbyjs.org/docs/mdx/.

### Motivation

I suspect TinaCMS is frequently used for a basic use case of creating a technical blog, supporting MDX would make it much more versatile.

**Comment by jsjoeio** [comment]
Chatted a bit in the tinaCMS Slack with @ncphillips about this. Here's a summary of the approach he suggested (in case anyone wants to help): 

- create a `gatsby-tinacms-mdx` plugin
  - use `gatsby-tinacms-remark` as an example of how to make it ([source code](https://github.com/tinacms/tinacms/blob/master/packages/gatsby-tinacms-remark/gatsby-node.js)) 
- get the fields `fileRelativePath` and `rawFrontmatter`.
- create custom hook `useMdxForm` that is similar to the `useRemarkForm`

**Comment by jsjoeio** [comment]
Verified that this could work by modifying my `node_modules` directly.

![image](https://user-images.githubusercontent.com/3806031/72637912-88327900-391f-11ea-8b39-a385418572c5.png)

Todos (for myself):

- [ ] create repo under personal account
- [ ] set everything up for `gatsby-tinacms-mdx` plugin
- [ ] test that it works
- [ ] create custom hook `useMdxForm` 
- [ ] test that it works
- [ ] open PR to tinaCMS monorepo

**Comment by PaulBunker** [comment]
This looks promising, I've forked your repo to see if I can get it setup somehow. I'd be interested in helping out in any way I can as this would be useful for me.

**Comment by ncphillips** [comment]
Aside: I updated to title. This issue–and @jsjoeio's PR–are specifically about Gatsby. I would consider MDX support for other frameworks to be unrelated.

**Comment by jsjoeio** [comment]
@PaulBunker would love to collab on this. Looks like you already saw my draft PR #707 but open to working together however makes most sense.

**Comment by PaulBunker** [comment]
@jsjoeio Excellent, so far I have cloned your separate repo into a local plugin. I got that working to a point. The raw MDX still contains the frontmatter so it's causing issues with the rendering inside the markdown field. If you click cancel the rendering seems to fix it's self for a second then starts an infinite loop adding tonnes of slashes 🤪 

I tried installing my fork of your repo with yarn so I could start figging into the code but that didn't go well and I got a mountain of errors. That's when I found the PR

I now have your PR locally. Next I'll try to figure out how to plug it all together and get back to where I was. It's not immediately obvious how to go about this but I'll have a poke about and see how far I can get. I still have to read the contributing documentation

I'm pretty sure I can get some time this sprint to work on this because the git workflow is better than my current strapi solution. I've added myself to the slack.

I've not used typescript yet this is the perfect excuse to add that feather to my cap.

**Comment by PaulBunker** [comment]
I'm not sure if this is the best place to post this. I've been at it for hours. Do you have any idea what I can do about this? I know it must build because 

`> gatsby-tinacms-mdx@0.0.1 dev /Users/paulbunker/repos/tinacms/packages/gatsby-tinacms-mdx
> tinacms-scripts dev

Building Package: gatsby-tinacms-mdx@0.0.1

lerna ERR! npm run dev stderr:
'tinacms' is imported by src/useMdxForm.tsx, but could not be resolved – treating it as an external dependency
'react' is imported by src/useMdxForm.tsx, but could not be resolved – treating it as an external dependency
/Users/paulbunker/repos/tinacms/packages/@tinacms/scripts/bin/scripts.js:33
  throw err
  ^

Error: /Users/paulbunker/repos/tinacms/packages/gatsby-tinacms-mdx/src/mdxFormHoc.tsx(21,26): semantic error TS2307: Cannot find module '@tinacms/form-builder'.
    at error (/Users/paulbunker/repos/tinacms/node_modules/rollup/dist/rollup.js:10151:30)
    at throwPluginError (/Users/paulbunker/repos/tinacms/node_modules/rollup/dist/rollup.js:16454:12)
    at Object.error (/Users/paulbunker/repos/tinacms/node_modules/rollup/dist/rollup.js:16509:24)
    at Object.error (/Users/paulbunker/repos/tinacms/node_modules/rollup/dist/rollup.js:16901:38)
    at RollupContext.error (/Users/paulbunker/repos/tinacms/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17192:30)
    at /Users/paulbunker/repos/tinacms/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24953:23
    at arrayEach (/Users/paulbunker/repos/tinacms/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:532:11)
    at forEach (/Users/paulbunker/repos/tinacms/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9358:14)
    at printDiagnostics (/Users/paulbunker/repos/tinacms/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24926:5)
    at Object.transform (/Users/paulbunker/repos/tinacms/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:26837:17) {
  id: '/Users/paulbunker/repos/tinacms/packages/gatsby-tinacms-mdx/src/mdxFormHoc.tsx',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  plugin: 'rpt2'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-tinacms-mdx@0.0.1 dev: `tinacms-scripts dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatsby-tinacms-mdx@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/paulbunker/.npm/_logs/2020-02-02T22_52_17_389Z-debug.log`

**Comment by ncphillips** [comment]
@PaulBunker you might want to try running `npm run bootstrap` from the root of the repo. 

Also I don't think that package needs to be referencing `@tinacms/form-builde`. Whatever is being imported from there could instead be imported from `tinacms`.
