### ISSUE TITLE
tina starter not working

### ISSUE THREAD

**Issue by Sceko** [tinacms/tinacms#556]
\my-tina-starter\src\components\bio.js
  17:28  warning  'useGlobalJsonForm' is defined but never used  no-unused-vars

**Comment by kendallstrautman** [comment]
Hi there, this warning shouldn't break the site but we could definitely remove that unused variable. Could you share a bit more about the issue or any other errors you see?

**Comment by muellercornelius** [comment]
I have the same warning. But just ignore it. It works fine.

**Comment by ncphillips** [comment]
The unused variable was originally put there [intentionally](https://github.com/tinacms/gatsby-starter-tinacms/blob/master/src/components/bio.js#L55-L68) to make it easy to switch between local and global forms. I'm not attached to that though.

I'm closing this issue because it's about [gatsby-starter-tinacms](https://github.com/tinacms/gatsby-starter-tinacms/issues) and not the core repo.
