### ISSUE TITLE
Make group-list actions configurable

### ISSUE THREAD

**Issue by nibtime** [tinacms/tinacms#589]
## Summary

It should be possible to opt-out from actions in the group-list component. I have a case, where I just want to allow the move action to visually arrange items in a grid, but editors should not be able to add or delete items. Currently that behavior is hard-coded [here (add)](https://github.com/tinacms/tinacms/blob/4a54b4cc61c58fa48752ea7db6bb32e603b6322c/packages/tinacms/src/plugins/fields/GroupListFieldPlugin.tsx#L95) and [here (delete)](https://github.com/tinacms/tinacms/blob/4a54b4cc61c58fa48752ea7db6bb32e603b6322c/packages/tinacms/src/plugins/fields/GroupListFieldPlugin.tsx#L160).
I know that it is possible to provide custom components, but I want just that component as it is, but with delete and add actions deactivated.

### Basic example

This could be implemented as optional field configurations `field.disableDelete` and `field.disableAdd`.

```typescript
{!field.disableDelete &&
  <DeleteButton onClick={removeItem}>
    <TrashIcon />
  </DeleteButton>}
```
``` typescript
<GroupListHeader>
  <GroupLabel>{field.label || field.name}</GroupLabel>
  {!field.disableAdd && 
    <IconButton onClick={addItem} primary small>
      <AddIcon />
    </IconButton> }
</GroupListHeader>
```

### Motivation

Sometimes you might encounter a data structure that represents a fixed size list of items rather than a record (group component). Can be a feature column on the home page for most important blog posts or something like a comparative pricing table with a fixed size of plans.

**Comment by spbyrne** [comment]
This is interesting, @nibtime. Recently when working on a Gatsby starter for Tina I had a similar desire, but instead of not being able to add/remove items it was not being able to edit items (you could only add, remove & reorder). I ended up essentially duplicating the group list code into my project and modifying it for my needs. You can have a look here:

https://github.com/tinacms/tina-starter-grande/blob/master/src/fields/authors.js

What this tells me is that there's a number of use cases very similar to group lists that could be covered with a few configurable parameters.
