### ISSUE TITLE
Add "raw mode" toggle for WYSIWYG

### ISSUE THREAD

**Issue by dwalkr** [tinacms/tinacms#626]
## Summary

The WYSIWYG editor should have a button in its toolbar to toggle between editing the raw content and editing in WYSIWYM mode

### Motivation

There are still some kinks with the WYSIWYG, and we should track them down and fix them, but in the meantime having a raw mode will allow editors to fix formatting gone awry from the CMS instead of having to open a text editor.

**Comment by nabeelvalley** [comment]
Not sure where I'd get started as I haven't contributed here before but I'd like to work on it if no one else is?

**Comment by mgielda** [comment]
Also potentially interested to work on this. Would you be able to point us where in the code to look? This is a very cool feature in netlify-cms, looks like it should not be very hard to implement, yet it would have immense value - it's often frustrating trying to find a problem with styling in WYSIWYG, whereas in plaintext errors in syntax are easy to spot. Also, since the CMS allows to edit content in place, this would be quite killer, doesn't seem like anything else can do this.

**Comment by DirtyF** [comment]
Ideally the raw mode would still allow people to insert links, images, tables from the toolbar.

**Comment by PaulBunker** [comment]
@mgielda the WYSIWYG lives [here](https://github.com/tinacms/tinacms/tree/master/packages/%40tinacms/fields/src/Wysiwyg) I've also got my eye on this feature/issue, would be killer for me too!

**Comment by ncphillips** [comment]
This issue is more _significantly_ complicated then it appears.

## Acceptance criteria for this feature:

* The Raw editor and the Wysiwyg must be entirely decoupled
* The two editors should share a common Menu component, with each setting editor setting it up to fit their needs.
* Each editor must implement an API for adding items to the Menu.


## Proposed Plan

* * A "Raw Mode" editor needs to be created. 
  * A plain textarea might work but I suspect the editing experience would be terrible.
  * A Codemirror based editor might be the best bet. That's what Forestry uses
* A layer of indirection needs to be added to the `Wysiwyg` defined in `@tinacms/fields`. It will probably look roughly like:
    ```jsx
    import { CodeEditor } from "@tinacms/code-editor"
    import { WysiwygEditor } from "@tinacms/wysiwyg-editor"
    import { ToggleModeIcon } from "./toggle-mode-icon"

    function Wysiwyg(props) {
      const [rawMode, setRawMode] = useState(false)

      const toggleModeControl = {
        icon: ToggleModeIcon,
        onClick: () => setRawMode(p => !p)
      }

      if (rawMode) {
        return <CodeEditor {...props} menuControls=[toggleModeControl] />
      } else {
        return <WysiwygEditor {...props} menuControls=[toggleModeControl] />
      }
    }
    ```
* The `Menu` component is totally coupled to prosemirror. It lives inside the [prosemirror plugin that adds the menu to the wysiwyg](https://github.com/tinacms/tinacms/blob/master/packages/@tinacms/fields/src/Wysiwyg/state/plugins/inline-menu/Menu.tsx#L28), and it's APIs know about prosemirror's actions. We will need to refactor and pull the base `Menu` component out of the Prosemirror plugins and make it ignorant of Prosemirror. That plugin would then have to setup the `Menu` with the Prosemirror actions. My gut says these menu styles should be moved to `@tinacms/styles` because our plan is to move the Prosemirror editor out of `@tinacms/fields` and we can't have circular references.


## Additional Background

The TinaCMS wysiwyg is based off the Forestry wyswyig.

Forestry has this feature. There is a toggle that switches between a Prosemirror editor and a Codemirror editor. The key here is that the button lives outside of both of these editors, neither of them know about the other, and they don't have a shared menu at all.

Here is a picture of the editor when the Prosemirror wysiywg is turned on. 

<img width="619" alt="image" src="https://user-images.githubusercontent.com/824015/74342841-845c1000-4d80-11ea-95ec-5a41c3d1ac41.png">

Notice that the wysiwyg menu is along the bottom, and a totally separate View Source button is in the top right corner. When that button is pressed, the wyswyg + menu is replaced with this Codemirror editor. That editor does not have a menu:

<img width="609" alt="image" src="https://user-images.githubusercontent.com/824015/74343259-28de5200-4d81-11ea-9e46-c79adbc6b36b.png">

This approach worked pretty well. Each editor was entirely separate, and can be developed in isolation, and has it's own menu. Unfortunately, because of the layout of the TinaCMS and the nature of Inline Editing I don't think this is a suitable solution.

**Comment by ncphillips** [comment]
## Implementation Plan

This issue is more complicated then it appears. 

The desired endstate is really:

* To have an amazing wysiwyg editing experience
* To have an amazing raw text editing experience
* To be able to transition between these two modes in a way that feels natural and consistent.

Due to the current setup of the wysiwyg, the last point is going to be a challenge. 

As it says in our PR template, small is beautiful. We strongly prefer to build large features by breaking them down into multiple smaller PRs. 

I think this can be done in at least 3 steps:

* Part 1: Add a `CodeEditor` to `@tinacms/fields`.
* Part 2: Allow the Wysiwyg to toggle between Code and Prose editors
* Part 2: Make a common toolbar for both editors 

### Part 1: Add a `CodeEditor` to `@tinacms/fields`.

At the end of Part 1 we will only have a basic code/text editor in @tinacms/fields that can be tested in teh storybook app. 

* Create a `CodeEditor` component in `@tinacms/fields`
* It should be entirely decoupled from the Wysiwyg
* It should only be used in the storybook; that is, _it should not actually be used in the wysiwyg_
* It should have a rudimentary menu; styling is unimportant.
* It could be implemented one of two ways:
  * A **plain textarea** might work but I suspect the editing experience would be terrible.
  * A **Codemirror** based editor might be the best bet. That's what Forestry uses

### Part 2:  Allow the Wysiwyg to toggle between Code and Prose editors

At the end of Part 2 the Wysiwyg component will allow us to switch between the Prosemirror editor and the CodeEditor 

* Both editors should allow you to add items to the menu through their props. This can be a highly specific API for now. A more general API for adding items to the menu can be addressed separately from this.
* A new component should wrap the Wysiwyg and:
  * selectively choose which editor to render
  * pass the editors what they need to toggle the edit mode

The Wysiwyg may end up looking something like:

```jsx
import { CodeEditor } from "./code-editor"
import { WysiwygEditor } from "./prosemirror-editor"

function Wysiwyg(props) {
  const [rawMode, setRawMode] = useState(false)

  const toggleEditMode = () => setRawMode(p => !p)

  if (rawMode) {
    return <CodeEditor {...props} toggleEditMode={toggleEditMode} />
  } else {
    return <WysiwygEditor {...props} toggleEditMode={toggleEditMode} />
  }
}
```

### Part 3: Make a common toolbar for both editors 

At the end of Part 3 both editors will have a common Menu. This will greatly improve the editng experience by making it consistent between both modes. Up until this point, there will be an awkward flip.

Right now, the Wysiwyg's `Menu` component is totally coupled to prosemirror. It lives inside the [prosemirror plugin that adds the menu to the wysiwyg](https://github.com/tinacms/tinacms/blob/master/packages/@tinacms/fields/src/Wysiwyg/state/plugins/inline-menu/Menu.tsx#L28), and it's APIs know about prosemirror's commands. 

This will require some refactoring. The base `Menu` component and it's styling will be pulled out of the Prosemirror plugins and made ignorant of Prosemirror. That plugin will setup the `Menu` with the Prosemirror actions using the more general API.

Once this is done, the newly decoupled `Menu` components can be used in the `CodeEditor`. 

## Next steps...

Taking this all the way to the end is a bit of a big project, but it can be broken down into smaller steps. 

I believe Part 1 and 2 would be pretty reasonable for someone in the community to take on. ( 

Part 3 is a much more significant refactor. Given the complexity of the prosemirror wysiwyg I would prefer if it was myself or @jpuri who took on that part. 

If anyone has ideas on how we can break this down even further, please comment below. I will update this issue as the plan is improved.

**Comment by jpuri** [comment]
Hi @ncphillips , plan looks good. Having a single menu is bit complex indeed.

**Comment by ncphillips** [comment]
Is it will be. But hopefully just styling and basic UI pieces. I feel like I could do the refactor fairly quickly.

**Comment by nabeelvalley** [comment]
Hi @ncphillips, the plan seems fairly straightforward, I'd like to give the first part a shot. Is there a suggested method/process for creating features - I don't really see much in the contribution doc

**Comment by ncphillips** [comment]
Awesome! 

You can just fork the repo and create a branch off of `master` to do your work. If you want some feedback, you can open a Draft PR so we can take a look at your changes. The process is mostly listed in the PR template:

https://raw.githubusercontent.com/tinacms/tinacms/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by nabeelvalley** [comment]
Thanks, will @ you if I need anything else!

**Comment by PaulBunker** [comment]
I would be happy with a simple monospace textarea and a toggle button.

**Comment by ncphillips** [comment]
I think that would be a good starting point. Part 1 and 2 could get to that point. Making the raw-code editor more advanced could be done later

**Comment by nabeelvalley** [comment]
So I've been looking at the way the other components are built, especially the current WYSIWYG editor and it looks like there's quite a bit going on there, would it make sense to have it be something more like the input component that only handles the plain text rendering? 

Additionally in terms of lifecycle and relationship to other components what sort of inputs and outputs will we be looking at?

**Comment by ncphillips** [comment]
Hmm, I'm not quite sure if I know what you mean @nabeelvalley. For plain text editing, there are `text` and `textarea` components available now, and @PaulBunker opened PR #791 to add a `code` field.

**Comment by nabeelvalley** [comment]
@ncphillips what I am referring to is, other than just rendering the component does the field need to have any outputs e.g. special `onChange` events or anything like that. The `TextArea` component that's there just implements a normal textarea, is that what we're looking for?

I looked at @PaulBunker's work, that made things a bit clearer, should I still try the CodeMirror implementation? It doesn't seem to be very straightforward or would you like to just go with the above mentioned `code` field?

**Comment by ncphillips** [comment]
Yeah, basically just the same API as a normal textarea. Once the `code` field is merged you could totally take a shot at making transforming it into a codemirror editor.

**Comment by PaulBunker** [comment]
@nabeelvalley  I'm happy to collaborate on this in what ever way works best. There's an issue with the current branch where the editor isn't populated with the content. Once that gets figured out we can work on the fun stuff with codemirror. I'm usually on the slack channel if you need a hand getting set up or you want to talk about how to get this going.

**Comment by nabeelvalley** [comment]
@PaulBunker sounds good, will hit you up on the slack channel 

@ncphillips who can I speak to about the current codemirror implementation on the WYSIWYG for the code section? The implementation looks quite involved

**Comment by ncphillips** [comment]
@nabeelvalley The implementation in the wysiwyg is not a great example to go off of. The reason why it's so complex is because it's nested within the prosemirror editor, and needs to stay in sync with it. 

You might be better off checking out something like [react-codemirror2](https://github.com/scniro/react-codemirror2)
