### ISSUE TITLE
Wysiwyg is lagging 

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#710]
## Description

Some lagging/performance degradation with the wysiwyg on the Feb 3rd release.

### Steps to reproduce

1. **setup Gra`gatsby new grande-test https://github.com/tinacms/tina-starter-grande.git && cd grande-test`
1. **Update Tina:** `yarn add gatsby-plugin-tinacms gatsby-tinacms-git gatsby-tinacms-json gatsby-tinacms-remark`
1. **Start Server:** `yarn start`
1. **Go to Blog Post:** http://localhost:8000/blog/introducing-tina-grande
1. **Edit Content:** click the `edit` button and type some sentences out.

I've also noticed this is to a much lesser extent in another site, but it's particular bad on Grande. I think this mayyy be isolated to the wysiwyg because the lagging doesn't seem to occur in regular text fields.

**Comment by TheFirstMe** [comment]
@ncphillips When I type type sentences quickly, wysiwyg doesn't work. The content I see is ahead of the content in the md files. Is this the issue you are referring to? I would also like to know if there's an option to disable wysiwyg so that the changes are only made to the md file when I hit save. Also disable git pushes on every saves?

**Comment by DirtyF** [comment]
@TheFirstMe you can set `pushOnCommit` option to `false`. See https://tinacms.org/docs/gatsby/configure-git-plugin/#options
