### ISSUE TITLE
Allow using useJsonForm hook in production

### ISSUE THREAD

**Issue by smashercosmo** [tinacms/tinacms#741]
## Summary

Similar to what has been done to useForm hook https://github.com/tinacms/tinacms/pull/520

**Comment by ncphillips** [comment]
Hey @smashercosmo, do you mean the `useJsonForm` hook from `gatsby-tinacms-json`?

**Comment by smashercosmo** [comment]
Yes

**Comment by ncphillips** [comment]
Right. Unfortunately Gatsby sites can't be edited in production. 

The main reason is that Gatsby does a significant amount of processing at build time that can't be replicated in a production Gatsby site. As such, the Gatsby pages cannot be reliably be rebuilt from content changes.

Another reason is that `gastby-tinacms-git` plugin requires a node server to write changes to the file system and make commits. This is not possible in the static production environment of a Gatsby site. Since `gastby-tinacms-json` is built on `gastby-tinacms-git`, it also cannot function.

**Comment by smashercosmo** [comment]
That's sad to hear :( I was hoping to replace netlify-cms (which allows editing in production) with tinacms. But anyway, thx for an explanation.
