### ISSUE TITLE
Option to abstract data sources and use an API/database instead of GitHub

### ISSUE THREAD

**Issue by chaddjohnson** [tinacms/tinacms#824]
## Summary

I really like TinaCMS quite a lot, though relying purely on GitHub for storing content is a bit limiting.

Is the Tina team perhaps considering abstracting data sources? For example, it would be great to also have the option to somehow use arbitrary API endpoints to retrieve and save data using a database.

### Basic example

Ultimately I'd like to store content via any medium.

### Motivation

This would expand Tina's capabilities and enable it to be used on more than just repository-based websites.

**Comment by chaddjohnson** [comment]
Maybe this is already possible using `useLocalForm` + `onSubmit` as in [this demo](https://github.com/ncphillips/demo-tinacms-firebase/blob/master/src/PageList/index.tsx#L35)?

**Comment by dwalkr** [comment]
Hey @chaddjohnson ,

I just wanted to follow up on this. You're bang on with the `onSubmit` idea. Tina tries to avoid being too opinionated about your workflow, but our initial implementations have focused around using local file storage and pushing to a git remote.

We've recently published some new docs that describe the fundamental building blocks of Tina. If you use these instead of the more opinionated Gatsby/Next.js helpers, you will find a lot more flexibility.

- [The CMS](https://tinacms.org/docs/cms/)
- [Forms](https://tinacms.org/docs/forms)

Hooking into the `onSubmit`, you can send the form data wherever you want when it's saved. And [registering a custom API](https://tinacms.org/docs/cms#apis) can help you abstract the behavior to apply it to multiple forms, if desired (but it's not absolutely necessary.)

Regarding the custom router: this is really only necessary when you need to implement the service layer yourself, and intend to do so in the same codebase as your website. `@tinacms/api-git` exists to expose a browser-accessible API for manipulating local files and interacting with a git remote. This could instead be achieved by creating a standalone application that exposes a web API, or by interacting directly with a third-party service that stores your content and allows you to make updates via API (as in the firebase example.)
